### ISSUE TITLE
Search columns parameter

### ISSUE THREAD

**Issue by harrythree** [robconery/massive-js#100]
In the Full Text Search example in the README, one of the params being passed is `columns` which is inside of an array. I tried adding additional columns to the array but instead of getting back an empty array when no results are found, I just get back null.

db.users.search({columns: ["first_name", "last_name", "username"], term: "harry", callbackstuff....

Am I using this correctly?

**Comment by xivSolutions** [comment]
There was an issue with the way the `ts_vector` terms were being concatenated. Should be fixed, added a couple tests. Now returns empty array when search term not found, and works correctly.

**Comment by stevenmwade** [comment]
@xivSolutions Adding multiple columns always returns an empty array even if there are valid results.

**Comment by xivSolutions** [comment]
Eek. I'll investigate more... re-opening.

**Comment by robconery** [comment]
Massive shouldn't return nulls - the first thing I want to be sure of is that you're checking *both values* of the callback. It should look like:

```js
db.users.search({columns: ["first_name", "last_name", "username"], term: "harry"}, function(err,results){
  //err should be null, results has the data
});
```

If no data is returned the query result will be `[]`. If that doesn't work, check to be sure you're getting results from Postgres:

```sql
select * from users where
to_tsvector(concat(first_name, ' ', last_name, ' ', username)) @@ to_tsquery('harry');
```

If that works I'll need to see your exact code.

**Comment by stevenmwade** [comment]
At least for me, running that `select` statements works in pgAdmin3.

**Comment by xivSolutions** [comment]
Closing again. See #154 and associated commit....
