### ISSUE TITLE
consider splitting massive into smaller packages

### ISSUE THREAD

**Issue by AdrianRossouw** [robconery/massive-js#123]
I've been going through massive.js to evaluate it for a project, and it kind of feels like it's trying to do too many things under this one banner.

I think that the core of the project is really something similar to clojure's [yesql](https://github.com/krisajenkins/yesql) (and it's js progeny [sqlt](https://github.com/eugeneware/sqlt) and [preql](https://github.com/NGPVAN/preql)). Basically: define your sql in a separate file.

Why not take the implementations for the massive-crud and massive-document, and split them into separate projects? They are pretty much built this way already.

Benefits: 

1. simplifies the core project. (so it is easier to attract potential contributors)
1. seeds the contributor ecosystem. (by showing how to extend massive)
1. provides opportunities to contribute. (for building your own massive-* modules)

**Comment by robconery** [comment]
The core of the project is making database work fun; sounds a bit goofy but that is, truly, at the core of it. For you, that might mean the SQL file thing, for others it's the document stuff. All three approaches together (the simple table stuff, the sql file/function bits, the document stuff) really capture the essence of working with Postgres.

That's part 1 :).

The second part is that I built this for a project I was working on, and these are the things I used (and still do) routinely. I think philosophically you have a point and it's something I've thought of doing later on as necessity demands (massive-docs, massive-files, etc). Right now the project is rather small and, in essence, I might even say it's "finished" in terms of things going in. 

This projects progenitor is a .NET library by the same name that was actually quite popular. I wrote it dedicated to SQL Server, but soon people came and offered a Postgres alternative, MySQL, MongoDB, Oracle... and that's when life got harder. At least for me.

I'm a huge fan of simplicity and *direction* - least possible action and all that. The project, at least for me, really couldn't be any simpler. Contributions have been pretty strong and have mostly focused on fine-tuning things with the odd improvement here and there. And there's always a chance to contribute.

So, in summing: I kind of like where we're at :).
