### ISSUE TITLE
Problem with update in sql file

### ISSUE THREAD

**Issue by belfour** [robconery/massive-js#132]
No matter how simple I make an update statement in a sql file I continue to get the following error:

syntax error at or near "﻿update"

SQL: update lists set item = 'test 2' where list_id = $1;

I have select queries running just fine.  My method in node:

    data.updListItem = function (li, next) {
            
        database.getDb(function (err, db) {
            if (err) {
                next(err, null);
            } else {
                db.updListItem(li, function (err, results) {
                    if (err) {
                        next(err, null);  <---- throws error here
                    } else {
                        next(null, results);
                    };
                });
            };
        });
    };

Seems like user error but I don't know where else to ask the question.  Are there any user forums for Massive?

**Comment by robconery** [comment]
Are you sure that's the exact contents of your file? Is it UTF-8 by chance? We just had a report of a BOM problem with UTF8 encoded files, caused by an IDE.

This error is from your database, showing the code above is interesting but what would be more helpful is to see the exact file contents.

**Comment by belfour** [comment]
UTF!  Curses!  Thanks for the help, UTF was the issue.

**Comment by robconery** [comment]
You can pull from recent - we just fixed this :)
