### ISSUE TITLE
Watch SQL files directory and automatically reload scripts

### ISSUE THREAD

**Issue by jmealo** [robconery/massive-js#133]
Kudos on Massive,

I just ported over [pgsanity](https://github.com/markdrago/pgsanity) from Python which uses ecpg to check the syntax of PostgreSQL files. I was thinking that we could have an option that watches the sql files and reloads them automatically as long as there isn't a syntax error (and optionally log/fire an event with a warning/error when a syntax error is encountered, and a notice/log entry when a reload occurs).

Additionally, perhaps we could check the syntax at load when we enumerate them at launch?

I'll try to put my [pgsanity](https://github.com/markdrago/pgsanity) port on NPM in the next week or so. The python version used generators and destructuring and so did I. I'll probably remove them so that it doesn't require ES6 functionality (destructuring requires a feature flag still).

Ideally it'd all be streaming but I don't have the time to make it pretty, if it's a live watcher running in process though I think that it'd be wise for nothing to block.

It's wroth noting that ecpg is not included with PostgreSQL or its development libraries. It was available in my path on OSX 10.10 but it's not available on Ubuntu without installing libecpg-dev, so this would need to be a feature flag unless someone uses NAN and wrap libecpg properly... (I don't have time to do this right now.)

Let me know if you're interested.

**Comment by dmfay** [comment]
Re: watching files, we're using Grunt in our dev environments and have a task set up via grunt-contrib-watch that restarts the server if anything changes, including in /db. Your scripts are really only going to change during active development -- I hope! -- so that feature would just be dead weight once deployed.

**Comment by jmealo** [comment]
@dmfay: My application is a REST API. My route handlers are stateless so route handlers can be hot swapped (loaded, unloaded, modified) without restarting the process. I need the same with SQL. I want to lint the files so in the event of a failed file transfer or to help during development I fail fast/early. If the syntax checking at load time isn't worth the trouble of dealing with ecpg I understand. Are you not interested in either features?

**Comment by dmfay** [comment]
Massive is Rob's project so it's his call in the end, I was just pointing out that there're already external solutions for most file-watching use cases. If you need it in production (which it must be said, albeit without knowing the particulars of your situation, does seem like the sort of thing that could go very wrong very easily) there are libraries such as https://github.com/fgnass/filewatcher or https://github.com/bevry/watchr that can do the same thing, so I wouldn't bet on the feature making it into Massive itself when it'd only take a little custom code to wrap it in something that kicks it over when a change occurs. That's the standard use case for promisification for example: Massive doesn't return promises itself, but multiple projects including ours wrap it with a converter.

Syntax checking on load does sound like it could be useful if it doesn't slow down startup too much, but I'd have to check it out for myself.

**Comment by jmealo** [comment]
In a cluster zero-time scenario it'd be much better to respawn the process allowing massive to redo it's initialization, but if you were to do that on lets say 8 workers, we're talking about a huge hit depending on the size of your DB. This is the obviously the safest way to do things (and probably best practice if you can stomach the CPU).

@robconery Effort would probably be better placed by supporting clustering and zero downtime deployments in massive, which would just be a parent worker doing all the initialization and then pushing that down to each worker. You could then send a signal or use REPL to tell the master to reinitialize massive and it could gradually respawn the workers as their connections empty.

I didn't test this yet, but I'm not entirely sure how ```$1``` placeholders would impact the syntax checking. I was using ``pg-promise`` and liked how my code looked. I'd need to figure out more about how connection pooling and a few other things work. I may be interested in being a major contributor to Massive depending on how it looks under the hood.

My first steps would be adding transparent temporal support and some helpers do ACL with RLS as well as a way to use the GUC or plv8 to store the web application user when doing audit logging and enforcing RLS constraints.

I haven't researched if ``EXPLAIN`` would be a safe substitute for syntax checking (I know that ``EXPLAIN CONTRIBUTE`` is not).

**Comment by robconery** [comment]
What you're asking for won't work with Node, at least as far as I understand what it is you want. There is no "zero-downtime hot-swap" as far as I know because of the way Node works (single thread/process) and the way modules work with NPM (static instances). It *has* to work this way, otherwise you get deadlocks and thread snarls.

As far as clustering goes (I assume you mean the Node kind) - Massive will work just fine in that case. PM2 is a great example of multi-process Node production support. But this only works if its governed by PM2.

So, to achieve what you want you would need what @dmfay is suggesting: a watcher process that restarts PM2 when SQL files change. Which could work, but this could/should also be governed by a deployment process (with shipit or something) and then... well it's literally just deployment.

Anyway, if you want to do this you can use something like [requre-reload](https://www.npmjs.com/package/require-reload) which, frankly, sounds like a disaster waiting to happen.

Now, to your problem: *how do you analyze and change a SQL command on the fly*? Use a function or a view and lint/push to Postgres as you need. That's what I would do.

**Comment by jmealo** [comment]
IMHO, PM2 served its purpose when cluster wasn't stable. Now that it's stable and the Node v4 rebirth has occurred it's time to embrace cluster. If someone is using PM2 and the workers aren't stateless to the point where a PM2 run service can be converted to a cluster service than it's not really stateless.

If you just add a "stateless" property to your modules you can easily do hot swap without respawing the process by checking for that and acting accordingly depending on how you reference your external dependencies. Things aren't going to grind to a halt, if a reference is held V8 isn't going to pull the module out from under someone who is using it. If all goes well and you delete the reference from the require cache it should be garbage collected when the last thing using it is finished executing or isn't referenced anywhere.

Depending on how mindful one optimizes their code for V8 and being disciplined to not rely on side effects and closures your memory usage, performance, JITing and ability to do things like hot swap are improved. That being said it sounds like Massive isn't safe to do that (most code isn't, closures are tempting and sometimes a must, it's just not a strong part of the JS community...) so running in a master process and then passing the initialization data to each of the workers makes the most sense to me.

* https://github.com/petkaantonov/bluebird/wiki/Optimization-killers
* https://nodejs.org/api/cluster.html
* https://github.com/doxout/recluster

**Comment by robconery** [comment]
Ah yes, cluster. Forgot about that :). No, using it is not something I'm interested in right now. Sounds like a horror show waiting to happen :).

**Comment by jmealo** [comment]
Understood, it's a lot to bite off, not relying on side effects and trying to use stateless and functional paradigms isn't natural or widely practiced in JavaScript. Forcing yourself to do so results in much more robust code, but it requires much more effort to write if you're flying by the seat of your pants with loosely defined requirements. It's nice to follow the practices, write a few hundred lines of code and it runs right the first time (never having run the file while coding)... it's the most satisfying feeling I've had developing. I'm still getting the hang of it but it's necessary in building high scalable, fault-tolerant applications.

If you're looking for a rush on a rainy day try to think in terms of minimizing side effects and mutability. It's kind of hard to do for a library like Massive. It's nice that you don't force promises or anything too opinionated.

**Comment by robconery** [comment]
I agree with you on distributed programming techniques helping with scaling, but I'd never try to re-implement Erlang in Javascript. That would be utter hell. A simpler answer is just to use messaging - something like Kue works really, really well and you don't write the code yourself.

I dig that you like what you see and where it's leading you, but I think you might be better served using a platform built for distributed programming. At least try out a queue like Rabbit or something.
