### ISSUE TITLE
terminating connection due to administrator command error

### ISSUE THREAD

**Issue by creole** [robconery/massive-js#134]
Hi,
how should I handle the case of an inaccessible Postgres server with this library (at least, that's what I assume it is)? Currently, my node app crashes with the following error:

    error: terminating connection due to administrator command
    at Connection.parseE (/home/ubuntu/workspace/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/ubuntu/workspace/node_modules/pg/lib/connection.js:366:17)
    at CleartextStream.<anonymous> (/home/ubuntu/workspace/node_modules/pg/lib/connection.js:105:22)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:764:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at _stream_readable.js:419:7
    at process._tickCallback (node.js:419:13)

Thanks!

**Comment by robconery** [comment]
I'm not too sure what your question is - are you asking  how you catch the error? What to do with it?

**Comment by creole** [comment]
Yes, how should I catch and handle it without letting my app crash?

BTW, I love the jsonb api and am curious to see what you will come up with when they release postgres 9.5.

**Comment by robconery** [comment]
I believe if you're using the latest you can just eval the error when you call `massive.connect`. If it can't connect, the db will be null and the error will tell you. What have you tried so far?

**Comment by creole** [comment]
I'm using your express example with db = app.get('db'); the connection was established fine, but then the postgres server must have somehow become unresponsive, so that the error was thrown when I called db.

**Comment by robconery** [comment]
Can you give me a code example with as much detail as you can...

**Comment by creole** [comment]
Sure:

    var express = require('express'); 
    var app = express();
    var massive = require("massive");
    var DATABASE_URL = 'postgres://etcetera';
    var connectionString = DATABASE_URL + '?ssl=true';
    var massiveInstance = massive.connectSync({connectionString : connectionString});
    app.set('db', massiveInstance);
    var http = require('http').createServer(app);
    var db = app.get('db');
    db.w.findDoc(1, function(err, result)
    {
        console.log('result[0] = ' + util.inspect(result[0], { showHidden: false, depth: null }));
    });

So the above is all fine, and result[0] gives the expected - well, result. Following calls with:

    db.w.findDoc(id, function(err, result){});

also work as expected, until one of them throws the error I mentioned above and crashes my app.

**Comment by robconery** [comment]
None of these methods should throw - can you send a stack trace?

**Comment by creole** [comment]
I thought a stack trace was what I included with my first post. Do you need more? If you do, you might also find it here: https://github.com/brianc/node-postgres/issues/821

The original commenter seems to have found a way to handle the error by using pg.on(...). Would exposing the pg object be an option?

**Comment by robconery** [comment]
Hmm - that's the driver code; honestly the only thing I can tell you at this point is to use a try/catch. Hard to diagnose the issue.

**Comment by creole** [comment]
OK thanks.
