### ISSUE TITLE
Not getting the database tables

### ISSUE THREAD

**Issue by aderbas** [robconery/massive-js#135]
I'm try to connect my database (postgres) using connectionString, apparently a connection is established but can not scan any table. 

```
var Massive = require("massive");
var connectionString = "postgres://aderbas:mysecret@localhost/test";
var db = Massive.connectSync({connectionString : connectionString});

db.articles.find({id: 1}, function(err,articles){  ... });
```
```
$ node test.js 
```
and get this error: TypeError: Cannot read property 'find' of undefined

the table exists in the database, obvious =p

**Comment by dmfay** [comment]
Check your schema permissions and make sure the user you're connecting as has access to it. I just spent way more time than I want to admit the other day figuring that out on our build server.

**Comment by aderbas** [comment]
Hi @dmfay The user is allowed to access the database and all the tables. I print on output the db object and have a list of functions on database but list of tables is empty. I added handler on connection and do not get any error.

**Comment by robconery** [comment]
I can almost guarantee this is a permissions problem. Can you try to connect as a super user just to be sure?

**Comment by aderbas** [comment]
```
grant all privileges on database test to aderbas
```
I did it for all tables too, just in case.

**Comment by robconery** [comment]
Give yourself ownership:

`alter database test owner to aderbas;`

**Comment by dmfay** [comment]
If those don't work, try going through this and see if that's the problem: http://stackoverflow.com/a/7758860

**Comment by aderbas** [comment]
@robconery the user already owns the database, by guarantee I did what you said.

@dmfay 
![captura de tela de 2015-10-27 16 13 15](https://cloud.githubusercontent.com/assets/12519019/10770360/a567477e-7cc9-11e5-9f82-46c250aba97d.png)

does not yet work =/

**Comment by dmfay** [comment]
What happens when you connect as the app user and `\dt`?

Also -- do your tables have primary keys defined?

**Comment by aderbas** [comment]
@dmfay I have already put the user 'Adherbal' as owner of the database, tables and sequences.

I tried to use another node client to postgres, (https://github.com/brianc/node-postgres) and got success, same connectionString.

**Comment by dmfay** [comment]
If your permissions are all in order and you're not using the whitelist/blacklist functionality about the only thing I can think of that'd prevent Massive from seeing a table is if it doesn't have a primary key column.

**Comment by aderbas** [comment]
Oh, the table "books" have a primary key but "articles" don't have. I create pk in articles and now works fine.

Thanks @dmfay for insisting on help =D

**Comment by dmfay** [comment]
no problem :)

**Comment by robconery** [comment]
Did this resolve? Also, @aderbas notice the owner in the table there is `postgres`, not your app user. Also, we use node-postures to hit the DB; it's the query (asking for schema info) that is failing. I was thinking this was permissions but it seems you didn't have keys set - just want to be sure this is solved.

**Comment by aderbas** [comment]
@robconery yep, is solved, I believe in my attempts to put everything aderbas as owner

**Comment by weagle08** [comment]
can anyone explain why a primary key is necessary on a table for massive to expose it as available table object?

**Comment by robconery** [comment]
I'll throw this back at you: can you explain why a primary key is *not* necessary? I do know that legacy systems and other completely wrong ideas lead to tables without primary keys... in that situation you're welcome to use straight up SQL to get around the issue. Or, perhaps, use a different DB tool that allows you to shoot yourself in the face :).

**Comment by dmfay** [comment]
Additionally: because one of the principal reasons to use table objects in the first place is that it lets you quickly and easily manage and save individual records, which are best tracked by a primary key.

**Comment by Atulvermaon18** [comment]
Not able to connect to postgres database, getting error, please tell me what I have done wrong

exports = module.exports = (connection, loaderConfig = {}, driverConfig = {}) => {
                                                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shoppertreat/postgres/index.js:3:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by robconery** [comment]
I suspect that `Unexpected token =` is the explanation you need. You just need `exports=.

**Comment by dmfay** [comment]
They raised #406 -- it's a Node version issue.

**Comment by bjnortier** [comment]
@robconery 

> I'll throw this back at you: can you explain why a primary key is not necessary? I do know that legacy systems and other completely wrong ideas lead to tables without primary keys... in that situation you're welcome to use straight up SQL to get around the issue. Or, perhaps, use a different DB tool that allows you to shoot yourself in the face :).

Disclaimer: Just looking into TimescaleDB, not an expert on that or Postgres.

TimescaleDB (https://www.timescale.com) is a time-series extension for Postgres. It doesn't use primary keys, well, not conventionally defined ones anyway. I would like to use MassiveJS (which is great, btw), with TimescaleDB, but seems like I can't at this point. Investigating further but I'll probably just use custom queries instead of db.foo.find() etc.

**Comment by robconery** [comment]
Ah - cheers thanks. I think this is the key para that I read:

>Time-series data is largely immutable. Writes primarily occur as new appends to recent time intervals, not as updates to existing rows. Both read and write workloads have a natural partitioning across both time and space.

I can see why they went with this approach... sort of. No need to find individual rows by a key and since you're not updating/deleting the whole idea of a key is moot. I might suggest, however, just using a set of views or functions? It seems the value here is the SQL extension - so dig in!

**Comment by dmfay** [comment]
Views would help with reads, but having to write through a function instead of the table API is a bit ugly. There _is_ already an exception for foreign tables since those can't have primary keys, so @bjnortier if you're interested in expanding that for time series stuff feel free to open another issue to discuss what needs to happen there!

**Comment by tylercollier** [comment]
For me it was permissions. I used [this hint about using `\z` from stackoverflow](https://stackoverflow.com/a/7336518/135101) on a particular table to realize I had not assigned permissions to the user properly (I had run my grant privileges without having first switched to the correct database using `\c`).
