### ISSUE TITLE
paging for FTS, is it possible?

### ISSUE THREAD

**Issue by lfreneda** [robconery/massive-js#137]
Hello there, sorry to bother you rob =(

How should I set limit/offset/order and how to count affected rows when querying with table.search?

```sql
db.users.search({columns :["email"], term: "rob"}, function(err,users){
  //all users with the word 'rob' in their email
});
```

I tried the same interface/contract for .find (providing a options object) but it didn't worked out

**Comment by robconery** [comment]
Good question :) I don't think it's built in yet for Full Text search. I might suggest using a SQL file for this - create the query you need then call it directly; better then muscling though an abstraction.

**Comment by lfreneda** [comment]
Thank you such @robconery :dancer:
