### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by ravestack** [robconery/massive-js#149]
How do you run the tests? I don't see any instructions for running them. The syntax looks like mocha, but every test failed.

**Comment by robconery** [comment]
it's `mocha .` and make sure you have a db that we can run the tests against called "massive":

```
createdb massive
```

**Comment by ravestack** [comment]
Alright, I did `createdb massive` and ran `mocha .`
I got this: `0 passing (2ms)`

I'm guessing wildly that this has something to do with this line in test/helpers/index.js:
`connectionString = "postgres://rob:password@localhost/massive";`

I can look into getting tests to work. Just curious if there's any particular local development-specific things I should look out for.

**Comment by dmfay** [comment]
If you didn't create the user `rob` with password `password` and superuser permissions on the massive db, that would definitely be a contributing factor.

**Comment by robconery** [comment]
Or just replace that with valid connection info. Also, use `mocha` without the dot - sorry my bad :).
