### ISSUE TITLE
Unhandled error event while inserting and violating db constrait

### ISSUE THREAD

**Issue by maca** [robconery/massive-js#15]
I must be doing something wrong but I cannot figure out from the documentation how to prevent node from crashing when an insert fails.

    var db       = require('massive');

    var databaseUrl = process.env.DATABASE_URL || 'postgres://localhost/dev'

    db.connect(databaseUrl, function(err, db){
      user = {
        email: 'mail@examle.com',
        crypted_password: 'password',
        secret: 'hello',
      }

      db.users.insert(user).execute(function(err, other){
        console.log(err);
      });
    });

node crashes:

  events.js:72
          throw er; // Unhandled 'error' event

My insert violates a unique constraint

**Comment by robconery** [comment]
This was fixed in 0.0.4...

**Comment by riginoommen** [comment]
how can we implement error handling in such a situation in node js.

my code is

    postEmployee: function(req, res) {    
        var pg = require('pg');  

        function createNewEmployee (cols) {
          // Setup static beginning of query
          var query = ["INSERT into employee "];
          query.push("(");

          // Create another array storing each set command
          // and assigning a number value for parameterized query
          var set = [];
          Object.keys(cols).forEach(function (key, i) {
            set.push(key); 
          });

          query.push(set.join(", "));
          
          query.push(") VALUES (");
          
          var set = [];
          Object.keys(cols).forEach(function (key, i) {
            set.push("'" + cols[key] + "'"); 
          });

          query.push(set.join(", "));

          // Add the WHERE statement to look up by id
          query.push(");" );

          // Return a complete query string
          return query.join(" ");
        }

        // Setup the query
        var queryText = createNewEmployee(req.body);
        

        var employeeConnectionString = "postgres://postgres:skedge@localhost:5432/skedge";
        var employeeClient = new pg.Client(employeeConnectionString);

        employeeClient.connect();

        var query = employeeClient.query(queryText);

        query.on("row", function (row, result) { 
            result.addRow(row); 
        });

        query.on("end", function (result) {   
            employeeClient.end();
            res.writeHead(200, {'Content-Type': 'text/plain'});
            res.write(JSON.stringify(result.rows, null, "") + "\n");
            res.end();  
        });
    },

and error log is

events.js:72
        throw er; // Unhandled 'error' event
              ^
error: duplicate key value violates unique constraint "employee_user_id_key"
    at Connection.parseE (/home/rigin/Work/Ops Portal/operations-portal-server/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/home/rigin/Work/Ops Portal/operations-portal-server/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/home/rigin/Work/Ops Portal/operations-portal-server/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by xivSolutions** [comment]
This does not appear to be a Massive-related issue, but more one of using the PG-Node Library. 

That said, when you make the call to `employeeClient.query(queryText);` You can (SHOULD!) either:

1. Add a callback which will include any error result:

```js
employeeClient.query(queryText, function(err, res) { 
  if(err) {
      // do some error handling
  } else { 
      // do some other stuff...
  }
});
```

Or, since you are using the evented model, you can try adding something like so:

```js
query.on('error', function(error) {
  //handle the error
});
```

See documentation for this on brianc's node-postgres wiki:

https://github.com/brianc/node-postgres/wiki/Query
