### ISSUE TITLE
Insert raw data on geometry type field (postgis)

### ISSUE THREAD

**Issue by aderbas** [robconery/massive-js#150]
I'm using the method 'save' to insert row on my table, it has a field of type 'geometry'. Supports the 'geometry' type? or I need to use raw data like: *ST_GeomFromText ('POINT (48.432044 -71.060316)', 4326)*

```javascript
var complaint  = {location: 'raw data?'};
db.complaint.save(complaint, function(err, saved){
   // 
});
```

**Comment by robconery** [comment]
I don't know if you're asking a question or submitting an issue. This is the Issue list - it's OK to ask questions about missing features etc but I don't have an immediate answer for this. Feel free to reopen if you have a problem.

**Comment by aderbas** [comment]
Okay, any idea how to enter into a postgres table with 'geometry' type? I'm try this
```
var q = "INSERT INTO ae_complaint (title, description, geom, date_created, user_created) VALUES ($1,$2,ST_GeomFromText ('POINT ($3)', 4326),$4,$5) RETURNING id";

db.run(q, ["foo", "bar", "valid lat valid lng", new Date(), 1345], function(err,res){ .... });
```
And I get this error: *could not determine data type of parameter $3*

**Comment by xivSolutions** [comment]
I agree wit h Rob, this sounds like it may not be directly a Massive issue, although it may be that the underlying PG driver doesn't know how to work with the geo data type. If I can, I'll experiment this weekend and see what there is to see. What happens of you include a hard-coded lat/long string value in the `POINT()' function in your SQL?

**Comment by aderbas** [comment]
I insert the line using the terminal and it worked. To work in Massive I did so:
```
var q = util.format("INSERT INTO ae_complaint (title, description, geom, date_created, user_created) VALUES ($1,$2,ST_GeomFromText('POINT (%s %s)', 4326),$3,$4) RETURNING id", point.lat, point.lng);
```

**Comment by xivSolutions** [comment]
Ahhh.. nicely done. :-)
