### ISSUE TITLE
Update or insert

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#151]
I don't think I see a way at the moment, but it would be great to have a feature like that. At the moment, what would be the best way to do that? My only ideas would be:

    for
        db.findOne // to find the id required for update
             db.update // if you find the id
             db.insert // if not

Granted this would possibly be the way you'd write it anyway, unless you run SQL commands in the background. The update also seems to only work if your values don't equal either, which means I may need to run checks and create a new object to send. Hopefully it could be easier and only updated the column that has actually changed. Is this easier when you are saving a column as `jsonb`?

**Comment by dmfay** [comment]
`db.table.save` emits an update if the primary key column is present in the data or an insert if not. You still need to have the id, of course. Not sure what you mean by it only working 'if your values don't equal either' -- can you clarify?

Updating jsonb data is an all-or-nothing proposition (no tweaking internal values) and it can sometimes be a little tricky, but I find that stringifying them before I pass them on to Massive usually takes care of it.

**Comment by stevenmwade** [comment]
@dmfay I think it may have to do with a unique column. I'm just playing around right now and I'm doing this:

    for (var i = 0; i < data.length/2; i++) {
			db.parts.findOne({name: data[i].name}, function(err, part) {
				if(part) {
					db.parts.save({
						id: part.id,
						name: data[i].name,
						status: data[i].status,
						fake: 'duper'
					}, function(err, inserted) {
						if(err) return console.log(err);
					});
				} else {
					db.parts.save({
						name: data[i].name,
						status: data[i].status,
						fake: 'super'
					}, function(err, inserted) {
						if(err) return console.log(err);
					});
				}
			});

I keep getting the error `duplicate key value violates unique constraint "parts_name_key"`. I would have just assumed, even though it's unique that it would update, granted it's not going to change so I don't need to update it anyhow.

Back to the point, I think. So `db.table.save` will only do an update if a primary key is required, which means I will always have to do a `db.table.findOne` each time I want to run an insert/update if the data I receive doesn't have their keys in the json?

**Comment by robconery** [comment]
As @dmfay said, you don't have to do the `if` statement here - `db.save` does this for you:

```
db.parts.save({
    id: part.id,
    name: data[i].name,
    status: data[i].status,
    fake: 'duper'
}, function(err, res) {
    if(err) return console.log(err);
});
```

Because you added the `id` field Massive will know to run `update`.

I think you're getting a duplicate error because 1) Massive doesn't know what your PK is or 2) You don't have a PK.

**Comment by dmfay** [comment]
I threw together a quick test and Massive isn't having any problems explicitly setting a unique field to its current value. You might check to see if you've got leftover data polluting your test environment, but the biggest problem I can see with that code is that you're using asynchronous functionality inside a for loop. Look into using something like `each` from https://github.com/caolan/async instead.

I'd write the inner part of your code as follows, though:

```javascript
db.parts.findOne({name: data[i].name}, function(err, part) {
    if (part) {
      part.name = data[i].name;
      part.status = data[i].status;
      part.fake = 'duper';
    } else {
      part = {
        name: data[i].name,
        status: data[i].status,
        fake: 'super'
      };
    }

    db.parts.save(part, function (err, parts) {
      if (err) { return console.log(err); }
    });
  });
```

will insert any parts that it can't find by name, and update those it can. & yes, if your incoming data does not include the ids you'll have to query the database for them, although finding each part name by name may prove to perform poorly at scale.

**Comment by stevenmwade** [comment]
Ok, I will try that. As for running the loop with async calls inside, I don't really care when the calls get run, just as long as they do and as long as they aren't running multiple times. Maybe that's just bad practice on my part and I should use `each` from async or just write a recursive function.

**Comment by robconery** [comment]
I didn't even notice the for loop - yeah that can cause all kinds of crazy. If you *must* do this there's a `saveSync` method you can use; but it's not meant for everyday kind of use. The `async` library is pretty good too but they have a big warning about executing code in a loop like that.

**Comment by stevenmwade** [comment]
Sounds good, thanks for the help!
