### ISSUE TITLE
Duplicate key error not on duplicate keys

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#152]
Currently getting said error:

`{ [Error: duplicate key value violates unique constraint "parts_name_key"]
  message: 'duplicate key value violates unique constraint "parts_name_key"' }`

The first two (out of ~5800+) names (varchar) keys are:

`900NTNNEK00000-NO_FW`
`900NTNNEG00000-NO_FW`

These are not the same, but are still somehow being rejected. This may be PostgreSQL or could be Massive.js. If PostgreSQL can't tell these two apart, then I have the wrong DB.

**Comment by robconery** [comment]
This is a Postgres error, Massive doesn't throw this. If I had to guess, I would say that Postgres can *probably* tell those two values apart and your test data isn't being cleared properly.

Triggers perhaps? Do you have a callback you're using?

**Comment by stevenmwade** [comment]
I'm using the same function from the other issue I wrote. I'm starting with a clean table and have limited the data set to only run two. If I run it from Node, the error happens when `this.db.query` runs the `pg` commands. I tried it straight in pgAdmin3 and it worked fine when adding the new value. I come from NoSQL and just learning PostgreSQL, so it could be my fault in that end.


Said function (currently fixing for async inside loop):

    for (var i = 0; i < 2; i++) {
			console.log(data[i].name);
			db.parts.findOne({name: data[i].name}, function(err, part) {
				if(part) {
					console.log('found');
					db.parts.save({
						id: part.id,
						status: data[i].status,
						fake: 'test'
					}, function(err, inserted) {
						if(err) return console.log(err);
						// console.log(inserted);
						// res.send(inserted);
					});
				} else {
					console.log('not found');
					db.parts.save({
						name: data[i].name,
						status: data[i].status,
						fake: 'super'
					}, function(err, inserted) {
						if(err) return console.log(err);
						// console.log(inserted);
						// res.send(inserted);
					});
				}
			});
		}

**Comment by robconery** [comment]
Would you mind telling me what this function is supposed to do? In general terms? It's sort of hard to understand what's going on and what you're trying to do etc.

**Comment by stevenmwade** [comment]
So we run tests every night on parts to pass certain parameters and they are, mostly, the same parts, but new ones are added every so often. Essentially the run the tests with jenkins and then need to post that json to PostgreSQL to have it displayed in a web environment. They don't have IDs so I used `id serial primary key not null` to create the ID. To be able to do the update you need the key so I have to go find the row matching the name so I can do that.

Essentially I need to find the key that matches the part name so I can either run an update or an insert.

**Comment by stevenmwade** [comment]
Well, it fixed itself with changing it to using `async.each`. Sorry to waste your time guys.

**Comment by robconery** [comment]
No worries! It's usually the culprit when head-scratching stuff happens :).
