### ISSUE TITLE
Full text search returning empty arrays

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#154]
I am getting this in two ways (v2.1):

    db.table.search({columns: ['one', 'two'], term; 'foo'}, function(err, data) {
        console.log(data);
    });

    AND

`db.table.searchDoc`

My table:

    id serial primary key not null,
    name varchar(20),
    status varchar(20),
    body jsonb

I would assume that because columns is an array it could take two parameters and `db.table.searchDoc` just returns an empty array and it essentially is just copied from the docs.

**Comment by robconery** [comment]
The columns need to be named the same as the columns in your table:

```js
db.table.search({columns: ['name', 'status'], term; 'foo'}, function(err, data) {
    console.log(data);
});
```

**Comment by stevenmwade** [comment]
They are, still results in null;

**Comment by robconery** [comment]
What is the err. Also, can you show me the *real* code; it's impossible for me to guess.

**Comment by xivSolutions** [comment]
@stevenmwade @robconery -
 Ok. There was a weird issue here. Fixed. The test was passing previously, and I'm not sure what was going on, but the code pushed addresses things (so far...). 

before applying the fix referenced, the 'search()' function would build the following:

```js
      db.products.search({columns : ["Name", "description"], term: "description"},function(err,res){
        assert.equal(res.length,4);
        done();
      });
```
would build sql:
```sql
select * from "products" where to_tsvector(concat('Name, ', 'description')) @@ to_tsquery($1);
```
which if copied to pgAdmin3 (replacing the $1 param with a hard string 'description', which appears in the `description` field for all four records in the table test data), would execute as expected, and return 4 product records. However, if we create a table per the OP like so:
```sql
create table "table"
(id serial primary key not null,
name varchar(20),
status varchar(20),
body jsonb)

-- add some sample searchable data...
insert into "table" 
    (name, status) 
values 
    ('john', 'good'), 
    ('tom', 'bad'), 
    ('jack', 'mediocre'), 
    ('jill', 'mediocre'), 
    ('tim', 'tim')
```
and then run this:

```js
Massive.connect({connectionString: constr}, function ( err, res) { 
    res.table.search({columns: ["name", "status"], term: 'tim'}, function(err, data) { 
      console.log(err);
    });
});
```
the resulting sql, same as previous, looks like this (some format as previously):
```sql
select * from "table" where to_tsvector(concat('name, ', 'status')) @@ to_tsquery($1);
```
BUUUUT, popping THAT into pgAdmin3 (with 'bad' replacing the $1 param) yields an empty result set.

I have NO IDEA why these two perform differently, but this is why the test passed before the fix. 

The fix just pushed up fixes this, and produces sql like so:
```sql
select * from "table" where to_tsvector(concat(name, ' ', status)) @@ to_tsquery($1);
select * from "products" where to_tsvector(concat(Name, ' ', description)) @@ to_tsquery($1);
``` 
Which appears to work in all multi-column cases.

**Comment by xivSolutions** [comment]
Closing for now. Sure wish I know why the statement against `products` worked, but the other did not. Possibly due to the use of keywords in the table/column names in the other case?

**Comment by stevenmwade** [comment]
@robconery Sorry for the late reply, there actually was no error. The result was just empty. Actual code:

    db.part_rules.search({columns: ['result', 'name'], term: 'warn'}, function(err, parts) {
			if(err) return console.log(err);
			console.log(parts);
			res.send(parts);
		});

Returns `[]`. If I take out `name` then I get an array of length 1396.

And this is just a question but when you use `searchDoc` is there a way to search on a document column that isn't named `body`?
