### ISSUE TITLE
Using concat in db.run returns null

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#155]
Sorry for all the issues! I'm playing around with Massive a lot because I'm learning PostgreSQL and going through a bunch of Pluralsight courses, anywho.

I was just doing some `db.run` to create a `tsvector` field for possibly running searches to compare to the on the fly `db.table.search` and seemed to run into a problem.

NOT WORKING: 

    db.run('select to_tsvector(concat($1, \' \', $2, \' \', $3))', ['super', 'duper', 'skates'], function(err, result) {
			console.log(result);
			res.end();
		});
    // returns null

WORKING:

    db.run('select to_tsvector($1 || \' \' || $2 || \' \' || $3)', ['super', 'duper', 'skates'], function(err, result) {
			console.log(result);
			res.end();
		});
    // returns [ { to_tsvector: '\'duper\':2 \'skate\':3 \'super\':1' } ]

Also, side not, using double quotes inside single quotes doesn't work, they have to be escaped.

**Comment by robconery** [comment]
I don't think this is an issue with Massive, you're trying to write SQL that's not working. If you want to know the problem make sure you console.log the error as well as the result.
