### ISSUE TITLE
Pooling configuration?

### ISSUE THREAD

**Issue by robinjmurphy** [robconery/massive-js#157]
Is there any way to configure the [connection pooling](https://github.com/brianc/node-postgres#client-pooling) options?

It looks as though the `pg` client is configured using the default values. Have you ever found the need to configure the pooling manually?

**Comment by robconery** [comment]
We started off with pooling, but when we load tested things we realized the pool wasn't acting in the way we thought it would.  I can't remember completely, but I do recall in testing we would routinely error out - the release connections wouldn't be recycled properly.

Anyway all those problems went away when we just went with the client settings; TBH I think pooling might be a tad buggy in the driver though the only reason I say that is we had errors when using it and they went away when we stopped.

The final bit of advice I got on this was from @datachomp who told me one day:

> if there's a chance we'll need pooling I'm not going to trust your shitty little library, I'll use pg_bouncer

So there's that :).

**Comment by robinjmurphy** [comment]
Thanks for the explanation.
