### ISSUE TITLE
Find and findOne with varchar primary key

### ISSUE THREAD

**Issue by kzar79** [robconery/massive-js#159]
If a table has a PK of type Varchar (or anything that in Javascript is a string) the call
```javascript
db.table.findOne("pkvalue", function(err, res) {});
```
fails, because the code interprets "pkvalue" as a where condition and not as the value of the PK to find.

Actually, it generates an exception in where.js because it expects an object and finds a string, so the 
```javascript
key.trim().split(/ +/)
```
 tries to trim a 0...

The solution is just to change
```javascript
if(_.isNumber(args.conditions)){
```
with 
```javascript
if(_.isNumber(args.conditions) || _.isString(args.conditions)){
```
in queryable.

**Comment by dmfay** [comment]
nice catch!

**Comment by eymengunay** [comment]
@dmfay I've seen that v2.1.0 has just been released but unfortunately doesn't include this pr. Should we expect a release including the fix anytime soon?

**Comment by xivSolutions** [comment]
@eymengunay @dmfay it looks like we have a few things that should probably be bundled up into a release in the near future. i know @robconery is travelling at the moment, and I also think we should review what's pending a release, and if there is anything else outstanding that should be. 

Ultimately that's all up to Rob, but it shoujld be coming, soon

@dmfay Thanks for staying on top of this stuff :-)

**Comment by dmfay** [comment]
Also, if you need to get by in the mean time and are willing to risk a little jankiness, you can track master or even a specific commit in your package.json ([link](https://docs.npmjs.com/files/package.json#github-urls)). But be sure to update once the release drops!

@xivSolutions it's no problem, without Massive I'd have had to write my own data layer from the ground up -- this is way better!

**Comment by eymengunay** [comment]
@xivSolutions @dmfay Thank you for the explanation. I'm already using the master branch although as you said it is not an ideal solution. 

I'm looking forward for a new release, thank you all for this awesome library :)
