### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by skeie** [robconery/massive-js#163]
Hi,

First of all, thanks for massive-js, I love it! 
I was looking for transaction, and i stumble over [this](https://github.com/robconery/massive-js/issues/81) issue. The issue is only open to collaborators, so I was wondering if you guys is working on it, and how far you come?

**Comment by robconery** [comment]
Decided to not do transaction support at this time - the abstraction is just too ridiculous. Best to use a single SQL file.

**Comment by skeie** [comment]
Thanks for the answer. Would you please state what you mean with `use a single SQL file`?

**Comment by robconery** [comment]
Read our README - you can pop a SQL file into a directory and execute it as a method with Massive. This is done within a transaction.

**Comment by skeie** [comment]
Yep, thanks, I knew that, I just didn't catch what you mean by use a single sql file, my bad.
