### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by squarejaw** [robconery/massive-js#164]
I pulled down the project, did an `npm install`, and noticed this:
```
npm WARN package.json massive@2.1.0 license should be a valid SPDX license expression
```
Looks like it might be [`BSD-3-Clause`](http://spdx.org/licenses/BSD-3-Clause.html)?

I also noticed a [reference to "SubSonic"](https://github.com/robconery/massive-js/blob/5196120ca52c2528593298ded835b52e01b6cf53/LICENSE#L10) in the LICENSE file, which I think might be a mistake.

**Comment by robinjmurphy** [comment]
Hi @squarejaw. I've updated this in #198 to remove the warning. @robconery might be able to explain the SubSonic reference in the license.
