### ISSUE TITLE
%$1% in db.run throwing errors and empty arrays

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#168]
I may just be using your syntax incorrectly, and if I am, I apologize.

This version gives an error `bind message supplies 1 parameters, but prepared statement "" requires 0`:

    db.run("select * from parts where name like '%$1%'", [name], function(err, parts) { 
			if(err) {
				console.log('ERROR: ', err);
				res.send(err);
			} else {
				res.send(parts);
			}
		});

This gives an empty array somehow:

    db.run("select * from parts where name like '%$1%'", name, function(err, parts) { 
			if(err) {
				console.log('ERROR: ', err);
				res.send(err);
			} else {
				res.send(parts);
			}
		});

This works fine:

    db.run("select * from parts where name like '%"+name+"%'", function(err, parts) {
			if(err) {
				console.log('ERROR: ', err);
				res.send(err);
			} else {
				res.send(parts);
			}
		});

**Comment by xivSolutions** [comment]
Yeah. You need to use the same concatenation style, but ni a manner Postgres understands. in other words, when you wrap your parameter placeholder inthe wildcard symbols you need to use the Postgres concatenation symbol:

```js
db.run("select * from parts where name like '%' || $1 || '%'", [name], function(err, parts) {
        if(err) {
            console.log('ERROR: ', err);
            res.send(err);
        } else {
            res.send(parts);
        }
    });
```

That SHOULD work.

**Comment by robconery** [comment]
Can you try....

```
db.run("select * from parts where name like $1", ["%rob%"], function(err, parts) { 
        if(err) {
            console.log('ERROR: ', err);
            res.send(err);
        } else {
            res.send(parts);
        }
    });
```
You have to pop the percent bits into the arg....

**Comment by stevenmwade** [comment]
@xivSolutions Ah, fantastic. Thanks. Sorry for the lack of knowledge!

@robconery I'm sorry I didn't specify that name was a variable, but I can see how that would work.
