### ISSUE TITLE
Having trouble using IO.js and passing arguments properly to a SQL File function

### ISSUE THREAD

**Issue by futuremint** [robconery/massive-js#169]
Passing an array of parameters to a query in a SQL doesn't work. ["You need to wrap your parameter into an array"](https://github.com/robconery/massive-js/blob/5196120ca52c2528593298ded835b52e01b6cf53/lib/runner.js#L48) is what I get back because args.js is blowing away the params array and replacing it with the default `[]`.
The reason why is because the first parameter is an array, however the args.js library that is used uses `instanceof Array` to check for the params arguments [as defined here](https://github.com/robconery/massive-js/blob/5196120ca52c2528593298ded835b52e01b6cf53/lib/arg_types.js#L10).  Because `params instanceof Array` already evaluates to false [this early in the stack](https://github.com/robconery/massive-js/blob/5196120ca52c2528593298ded835b52e01b6cf53/index.js#L265) I'm not exactly sure a fix for this can be put into massive.js itself, it might require a patch to args.js for them to use `Array.isArray` vs `instanceof`. [The offending code in args.js can be found here](https://github.com/joebain/args.js/blob/b7de109a190c86b0b499126209a0f50216e50a36/Args.js#L76).

I'm submitting this here first to see if you have an idea of how to handle this within massive.js itself (and I'd happily write up and send a PR to fix this with some input on how you think massive.js could fix this issue).

**Comment by robconery** [comment]
Thanks :) - I *think* I understand what the problem is but it always helps to see the code causing an error so I can repro it. I'm having a hard time following the problem.

**Comment by futuremint** [comment]
I just looked at your unit tests and it looks like you have this covered there... so I'm trying to narrow this down more in my setup. I'm using nw.js 0.12 which has io.js 2.5.1 in it I don't know if that is the problem or not.
Its just a basic sql query like this 
```
SELECT * FROM a_table WHERE something = $1 AND something_else = $2
```
And I'm just calling that from nw.js like so:
```
pgsql.findAppReleaseEnv(['First Thing', 'Second Thing'], function(err, rs){console.log(rs);})
```
When I step through the debugger that first argument is false for `instanceof` almost right away, yet is true for both `_.isArray` and `Array.isArray`.  So I'm kind of baffled :)

**Comment by robconery** [comment]
Interesting. So your file is called `findAppReleaseEnv` and you're invoking it and passing in the array, correct?  Yes - that works and is tested and yes, we're using Node proper.

What is nw.js? Do you have access to Node?

**Comment by futuremint** [comment]
I just ran your unit tests using io.js 2.5.1 and they pass:
```
      ✓ executes productByName with multiple params and callback
```
So... I'm going to go with this is something specific to how I'm calling it that is broken.  You can close this issue if you want, I think I may be premature in thinking that it your fault :)

Yes, nw.js used to be called node-webkit. http://nwjs.io

**Comment by robconery** [comment]
Ahh - OK. I'll  leave it open for now - it could be something else that's tripping things up. If you want to pop your code in here I'll see if something catches my eye. Cheers...

**Comment by futuremint** [comment]
Ok, I just figured out what the problem is.  Its specific to nw.js.  
Because nw.js has [different "contexts"](https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts), the array I'm passing in is created in the "window" context (from the DevTools, also from the JS on the HTML page, which is the window context), but massive.js is running in Node's context, therefore `instanceof` will be different because the prototypes will be _different_ arrays (the incoming param from Window's Array, and massive (and arg.js)'s from Node's Array.

So, feel free to close this is you want, this is basically an annoyingly subtle user error with nw.js :)

**Comment by robconery** [comment]
Ahhh - yeah just went through this with Electron :). Confusing to have Node basically running in both places... and modules available separately. Crazy! Glad you solved :).
