### ISSUE TITLE
Deleting documents using JSON-style matcher won't work

### ISSUE THREAD

**Issue by vincentgiraud** [robconery/massive-js#170]
This works:
db.doggies.destroy({id : 2}, function(err,res){
  //stinky smelled horrible
});

This doesn't:
db.doggies.destroy({"body ->> 'name'" : "Stinky"}, function(err,res){
  //deletes records where name is "Stinky"
});

Tested on PostgreSQL 9.4.4

**Comment by xivSolutions** [comment]
As I recall, the `destroy()` method is not implemented currently in a manner allowing criteria against documents. The current implementation only works against column-based criteria. 

I'm thinking this is a candidate for an enhancement. 

@robconery thoughts?

**Comment by dmfay** [comment]
That changed a little while back when I added support for JSON traversal in the find-style args. This unit test passes:

```javascript

    it('deletes by matching json', function (done) {
      db.docs.destroy({'body->>title': 'Starsky and Hutch'}, function(err, deleted) {
        assert.equal(deleted.length, 1);

        db.docs.find({id: deleted[0].id}, function (err, found) {
          assert.equal(err, null);
          assert.equal(found.length, 0);
          done();
        });
      });
    });
```

Note the omission of the single-quotes around the JSON field name ("body->>title" vs "body->>'title'"); Massive adds those itself after splitting on the possible operators. Vincent, that's probably what's messing your call up -- give it a shot without those.

**Comment by dmfay** [comment]
Looks like the docs are incorrect -- sorry about that! I'll see if I can make it a little less sensitive about whitespace at the very least though.

**Comment by vincentgiraud** [comment]
Yes, that did work!

**Comment by dmfay** [comment]
#171 allows pretty much any legal combination of whitespace and quoting so the docs shouldn't need to be updated. I don't know when Rob's planning to release the next version though.
