### ISSUE TITLE
You need to wrap your parameter into an array

### ISSUE THREAD

**Issue by evilpacket** [robconery/massive-js#173]
node version: v4.2.3
massive-js version: 2.1.0

I'm loading a simple sql query out of a file, when I call that function the arguments are never passed in. I did some debugging and it looks like the params get passed into options and params set to [] after they go through var args = ArgTypes.queryArgs(arguments);

```
db > db.advisory.fetchOne(['1', '2', '3'], console.log)

I logged out just after ArgTypes.queryArgs returns and this is what it gives.
{ sql: 'select * from things where id=$1 AND allowed_scopes ?| $3\n',
  params: [],
  options: [ '1', '2', '3' ],
  next: [Function] }

db > { [Error: You need to wrap your parameter into an array] message: 'You need to wrap your parameter into an array' }
```

**Comment by dmfay** [comment]
It works in code but fails as you described using the REPL. Looks like a bug in Args-JS -- it's using `instanceof` to check whether parameters are arrays and this seems to be one of the weird edge cases where that returns a false negative.

I submitted a fix to Args-JS here: https://github.com/joebain/args.js/issues/22

**Comment by dmfay** [comment]
Args.js integrated the fix and posted a new patch release. Update your dependencies recursively (or just remove node_modules/massive and `npm install` again) and the problem should be gone.

**Comment by xivSolutions** [comment]
Nice!
