### ISSUE TITLE
Is it possible to move sync part in separate lib?

### ISSUE THREAD

**Issue by btd** [robconery/massive-js#174]
`deasync` is hackery native addon. Native addons create a lot of pain while doing app deployments (build server can be not the same as deployment), in some situations i cannot just do `npm i --production` and zip folder, because of such native addons.
I would like to propose create second lib `massive-sync` and move every sync part to that lib. I would like to make PR if it is ok.

**Comment by pkwnz** [comment]
I am interested in this one too, because while this feature is useful, it seems like the original author of the module has big reservations about its use. So, it would be cool if we could choose to leave it out.

**Comment by robconery** [comment]
Yeah I need to move it out, but I can't do that until we rev to 3.0 as it's a breaking change.

**Comment by robconery** [comment]
This will be removed in v3.
