### ISSUE TITLE
A way to remove white-space from query

### ISSUE THREAD

**Issue by Aedaeum** [robconery/massive-js#175]
I have a field which is set to use up to 30 chars and if not all 30 chars are used, when I query for that field, the unused chars are filled with spaces. Is there a trim method that can be called on the query to remove that white-space before the data gets returned? Or a setting/option that can be set to auto-trim all results from a query.

**Comment by dmfay** [comment]
Ideally you should be using the `varchar(n)` type if you want to store and retrieve variable-length strings -- by using `char(n)` you're telling it "data in this column is always 30 characters long no matter what, pad it out if necessary", so it's just giving you what you've asked for.

If you can't change the column type for whatever reason, you can use Postgres' own `trim()` in a SQL script or function, or map your results through something that calls JavaScript's `string.trim()` on the receiving side, but there's nothing in Massive that will do it for you.

**Comment by Aedaeum** [comment]
Ah, okay, I didn't know that. Thanks :smile:
