### ISSUE TITLE
db.save returning undefined

### ISSUE THREAD

**Issue by stevenmwade** [robconery/massive-js#179]
I honestly don't know why this isn't working as it's modeled after something that is working, but this save does not error but also doesn't save and comes back undefined. I can put the actual `card` object in, take out `barcode`, etc. Doesn't work.

    var card = { id: 159, barcode: '', form_factor: 3 };    // var card = req.body.card;
    db.cards.save(card, function(err, savedCard) {
			if(err) {
				console.log(err);
				return res.send(err);
			} else {
				console.log(savedCard);  // undefined
			}
		});

    CREATE TABLE cards
    (
            id int primary key NOT NULL,
            barcode character varying(250),
            form_factor integer REFERENCES form_factors (id)
    )

**Comment by stevenmwade** [comment]
Changed it to run a SQL command and works fine. Something is getting messed up on the way.

		var cardSQL = 'INSERT INTO cards(id, barcode, form_factor) VALUES ($1, $2, $3);';

		db.run(cardSQL, [card.id, card.barcode, card.form_factor], function(err, savedCard) {
			if(err) {
				console.log(err);
				return res.send(err);
			} else {
				console.log(savedCard);
			}
		});

**Comment by xivSolutions** [comment]
@stevenmwade - Does the card with `id = 159` already exist int he database? If not, the problem is that `save()` is assuming it does, and trying to update an existing record which is not there. 

If you are not using auto-incrementing Id's, you will need to explicitly call `insert()` instead of 'save()`
