### ISSUE TITLE
find with arguments returns empty array.

### ISSUE THREAD

**Issue by ymitis** [robconery/massive-js#18]
Is anyone else not getting results when issuing a find command with arguments?  I'm trying to connect to MySql.  The following code returns an empty array:

db.Users.find({id: 1}).execute(function(err, users) {
                if(err) {
                    console.log(err);
                    //callback({error: err}, null);
                }
                else {
                   console.log(users[0].username);
                    //callback(null, users);
                }
            });

However the following returns the user:
                db.run('SELECT * FROM Users WHERE id = 1',function(err, users) {
                if(err) {
                    console.log(err);
                    //callback({error: err}, null);
                }
                else {
                   console.log(users[0].username);
                    //callback(null, users);
                }
            });

Also note the following returns the entire collection of users:
                db.Users.find().execute(function(err, users) {
                if(err) {
                    console.log(err);
                    //callback({error: err}, null);
                }
                else {
                   console.log(users[0].username);
                    //callback(null, users);
                }
            });

The execute function in mysql.js ....

   client.query(sql, params, function(err, results){

  The sql variable value =  SELECT * FROM Users WHERE "id" = 1

Notice that field name id is in quotations, I don't think it should.

Is there something I'm doing wrong?  or is it a bug?  I haven't been able to identity the bug yet but I will keep looking.

**Comment by robconery** [comment]
Shoved MySQL out; no longer supporting in v2. **Although** I think this problem might come from a local implementation bug *or* from improper error catching which was fixed in 0.0.4.
