### ISSUE TITLE
jsonb_set for document update?

### ISSUE THREAD

**Issue by seymores** [robconery/massive-js#181]
Hi,
I am wondering is there is plan to make use of Postgresql 9.5's jsonb_set to finally have document update that doesn't overwrite.

I cooked up something quick here, https://github.com/seymores/massive-js/blob/master/lib/document_table.js#L58

The obvious problems that I can see are:
 1. Depends on Postgresql 9.5's jsonb_set
 2. Column must be jsonb type

**Comment by dmfay** [comment]
I'm all for the feature itself, and the problems don't sound that bad -- `updateDoc` is a new function so anyone running < 9.5 can just keep going with `saveDoc`, and jsonb is better for storage anyway. Can you add some tests and submit a pull request?

Also you're pulling `args[pkName]` out into `plVal` and not doing anything with it, so you might want to check that out.

**Comment by seymores** [comment]
Happy to write the tests and do the PR.

I tried running the tests on my local but am stuck at
```
    Document updates
       1) "before all" hook
       ...
      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
I have created the test database to match `"postgres://rob:password@localhost/massive"` and tested to work fine using psql.

Any idea? :-(

**Comment by xivSolutions** [comment]
Did you set the conn string in the `test/helpers/index.js` file?

https://github.com/robconery/massive-js/blob/master/test/helpers/index.js

And, did you add `rob` as a user, with the password `password`?

**Comment by seymores** [comment]
Thanks.
Turned out the 'rob' account doesn't have admin permission to create extension.
    
      'permission denied to create extension "pgcrypto"'

**Comment by seymores** [comment]
@dmfay 
Completed a working and test backed updateDoc, see https://github.com/seymores/massive-js/blob/master/lib/document_table.js#L58
and the test spec here https://github.com/seymores/massive-js/blob/master/test/document_update_spec.js

However I come to think that the function name 'updateDoc' is not appropriate because it can only update one attribute at a time, limitation of `jsonb_set `.

I am thinking of renaming the function to `updateDocAttribute` but just want to run by you if you think the name is better than `updateDoc`.

**Comment by dmfay** [comment]
oh cool! What about `setAttribute` for the name? It's more concise but still gets the point across.

**Comment by seymores** [comment]
Done.
Creating a PR shortly.
:-)
