### ISSUE TITLE
.find() without limits

### ISSUE THREAD

**Issue by mattjburrows** [robconery/massive-js#183]
Hello,

I was wondering whether there is anyway to run the .find() method without having the [default of a 1000](https://github.com/robconery/massive-js/blob/master/lib/queryable.js#L100) set? I'd like to avoid setting a higher arbitrary value.

Many thanks in advance.

Matt.

**Comment by dmfay** [comment]
Not at present, but it wouldn't be too difficult to implement -- check for an override in `args.options`, probably. Feel free to submit a pull request!
