### ISSUE TITLE
`findDoc` and `searchDoc` with columns other than `body`

### ISSUE THREAD

**Issue by robinjmurphy** [robconery/massive-js#187]
It would be great to make use of the `findDoc` and `searchDoc` features with any column. At the moment they're only usable if you subscribe to the `body` column name convention and meet the requirements that are made on the primary key.

As an initial suggestion, it would be great to be able to do:

```js
db.products.findDoc('attributes', { category: 'fruit' }, function (err, doc) {
  // ...
});
```

In this example the first argument is an optional column name that would default to `body` if omitted.

**Comment by robconery** [comment]
Look OK to me - if you're up for it.. have at it!

**Comment by robinjmurphy** [comment]
Cool. Will dig in an see how big a change it is to the current implementation.
