### ISSUE TITLE
Anyway massive way to manipulate array?

### ISSUE THREAD

**Issue by seymores** [robconery/massive-js#202]
I may missed this but I don't see any easy way to manipulate array data of array type column.
Is this planned or something already in?

**Comment by dmfay** [comment]
Storage and retrieval work pretty much how you'd expect (look for tests in table_spec and queryable_spec dealing with `product.tags`), and `find` etc can use the contains/contained by/overlap operations like you'd use != or any other operation. Anything else you're going to need to script.

**Comment by xivSolutions** [comment]
Depending on your needs, you can also use Postgres' `array_to_json` See[THIS link](http://www.postgresql.org/docs/9.3/static/functions-json.html) function, as well as all the other array functions. This is a perfect use-case for SQL files in Massive. 

Might be worth looking into adding some array-to-and-from-json to the API here at some point.

**Comment by seymores** [comment]
I am sorry -- I should have say I am already using the sql file to do those array manipulation, particularly appending data.

@dmfay thanks, and at some point there should be a doc entry about this.
@xivSolutions Got it, thanks.
