### ISSUE TITLE
Full text search indexes - configuration?

### ISSUE THREAD

**Issue by pkwnz** [robconery/massive-js#205]
First of all, awesome project very interesting.

Please note I am not an expert on Postgres full text search, so hopefully I have the concepts right (I am looking to use it to replace other search facilities to simplify architecture for small-midsize projects) 

As I understand it, when using Search or SearchDoc MassiveJS will automatically create the required index if it does not already exist (i.e. it creates a permanent index to optimise for next time)

My question is, can this be configured in some way - does it use the "default configuration" and is it GIN or GIST?

I suppose that if I wanted to do something special I could bypass these commands and use the plain SQL approach to send the commands I want?

Do you use the postgres-node library and if so would it be possible to access via that in case of a problem with the way massive does things?

Thanks very much for this awesome project!

**Comment by robconery** [comment]
Thanks! The search index is GIN as that's what you use for JSONB. We create the index on the fly only in the case of a jsonb document - not for regular tables. The one thing you would want to change, most likely, is the case of reducing the index size by deciding which fields in your document you would want to index. Right now we do all of it using `jsonb_path_ops` - which says "traverse my document and index every key".

Most likely you won't want that - so you can just create the table yourself and you can still use Massive to query it. We do expect the jsonb to be called `body` and the search field to be called `search` however.

We use node-pg and we have a myriad of workarounds - Massive is just a query tool that's designed to help, not impose a system. For instance one thing I do regularly is popping SQL in a file so I can execute it as a function (JS function). You can also just run a query using `run`.

**Comment by pkwnz** [comment]
Very cool. I am looking at using this for two very cool upcoming projects... I really like the philosophy and approach.

I have a couple of somewhat-related questions:

1) Regarding "We use node-pg [...]", I understand this to be "brianc/node-postgres" - do we need to "npm install pg" ? and will I get the native bindings?

2) can we access the connection (pool) object from node-postgres that massive is using to do queries on the same pool ... or is this necessary ... or what do you recommend to combine massive with accessing via node-pg directly (how do I :) ) ?

3) Im slightly confused about "and the search field to be called search " - I am a bit unclear why we need the "search" field. Is this the body field redundantly stored but transformed into a ts_vector? As I mentioned I am not an expert on Postgres search... I guess I thought we only need the body, and then the index would transform the body into the right form

4) I also see now the document-database stuff (creating a document from JSON, GIN indexing it automatically etc)- very cool. I was planning to do something very similar manually so that I could create not just an id column, but also columns for some FKs - in order to make joins with other tables efficient. Basically I want search within documents and FK joins to other documents. I am wondering if there is another way I should be looking at this - this might just be a roll-your-own situation, but any thoughts welcome :)

Sorry for the barrage of questions, I think I am done :) I really appreciate your help!

**Comment by robconery** [comment]
> Regarding "We use node-pg [...]", I understand this to be "brianc/node-postgres" - do we need to "npm install pg" ? and will I get the native bindings?

npm does this for you - you don't need to worry about the driver nor how to access it.

> what do you recommend to combine massive with accessing via node-pg directly (how do I :) )

You don't need to, but if you want to you can `require("pg")` whenever and wherever you want. But I would advise not doing that. Massive is using the connection pool that pg provides - it's all managed for you. If you want to run SQL directly, we have a method for that: `run` or, like I said, just pop a SQL file into your `/db` directory and we'll read it in and execute it.

> I guess I thought we only need the body, and then the index would transform the body into the right form

If you're going to use `jsonb` you can't set a trigger to pull the `tsvector` values out. It's kind of complicated - what we do is populate the search field on save (which is separate from the `body` field, which is `jsonb`). If you create your own document table, just be sure it looks like ours is I guess what I'm saying :).

> . I am wondering if there is another way I should be looking at this - this might just be a roll-your-own situation, but any thoughts welcome :)

If you need joins then documents are likely not a good way to go. I tend to view a document in the scope of a single transaction - in fact I'm doing through this design exercise right now. Just put all the information together and then learn the JSONB functions so you can effectively query it later on.

**Comment by pkwnz** [comment]
Thanks, great answers to my questions.

I am very excited about massive.

I would like to respectfully disagree on the issue of documents and joins though. I believe such a fusion is and will be possible, and will greatly simplify app design. Mongo and the like fall down, not just because they are immature, but because they fail to appreciate the usefulness of relational database system in simplifying the model of a system. While you can use DDD and the like, I actually think this is a distraction. Just my 2 cents though. Maybe I will build something extra on/for massive :-)

**Comment by dmfay** [comment]
We're using jsonb fields mixed in with relational structures and it's going fine, although in our case the jsonb is basically pulled and pushed as a single unit so we're not doing any heavy-duty searching. But if you create your document table with the structure Massive expects and then add your FKs and other columns on top of that, you should be able to use Massive's document functions for JSON manipulation and searching and the standard table functions for everything else.

**Comment by robconery** [comment]
@pkwnz I think you misunderstand me :). Mongo, Cassandra, Riak - they don't fall down. In fact they power some of the biggest data stores you can find - Cassandra in particular (Facebook). These are highly-tuned K/V stores with purpose-driven schema, relational theory doesn't come into it *at all*. There is absolutely *nothing* immature about these systems.

I'm not knocking joins - one of my favorite document stores (RethinkDB) uses joins to keep the indexes and tables trimmed down. It works and it's lovely. But it distracts from the possibilities of using document storage.

For instance: if you use DDD (since you brought it up) - you can easily conceive of a document/entity. Saving that entity transactionally as a document make perfect sense. I tend to go one step more than that, though. 

If you are into "Event Sources" (in the Fowler sense) - you can simply store the results of a given event as a single document. For instance a Checkout - store all the information gathered during the checkout. When Stripe calls back, save that as a PaymentResult or Transaction.

Querying documents is incredibly easy - there's absolutely *no reason* to use relational systems outside of a transactional (OLTP) environment. We don't need to worry about disk space. Data rules can live in your app instead of enforcing integrity, and the transactional guarantees are provided by the documents themselves.

Before you think I'm being a NoSQL fanatic - please know I started life as a DBA :). I don't ever take data lightly and I love relational systems as much as I love docs. I've found they both work exceedingly well :).

**Comment by pkwnz** [comment]
@dmfay Thanks for this, great to hear :)

@robconery probably the wrong place to continue this conversation, but it's fun so let's do it anyway ;-) 
My comment was about Mongo specifically and a few other systems - not all NoSQL systems. I don't mean to be overly negative about it - I'm sure Mongo works really well for some projects. But I would argue other NoSQL systems or very often modern relational-hybrid systems (Postgres, HANA any modern RDBMS with search and document support) would be a better bet for many teams and products. I absolutely agree that you can use the right techniques to work with document stores effectively without relational capabilities, and for analytics and search relational capabilities are of low importance. 

But the point I was mostly trying to make is that I think that Postgres actually gives many teams something much more useful: the ability to leverage some of the document store facilities (like fast search) alongside useful relational capabilities for processing requests which is really cool :-)

Thanks again for Massive, and for your comments above.  I am considering doing what dmfay is doing.

**Comment by robconery** [comment]
Cheers :)
