### ISSUE TITLE
Namespace file queries based on directory

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#21]
Right now we read in the files and drop them right on the root namespace. Would be better to have namespacing by directory. We currently have `glob` installed but not sure how to handle this best.

**Comment by xivSolutions** [comment]
This works...I think. Could stand additional exercising + tests. I'll get to that after work tomorrow.

**Comment by robconery** [comment]
There was something wrong in the load up - it was throwing and wouldn’t start. I’ll take another shot at this in a bit - had an idea last night at 2am :(



On March 5, 2015 at 7:44:44 AM, John Atten (notifications@github.com) wrote:

This works...I think. Could stand additional exercising + tests. I'll get to that after work tomorrow.

**Comment by robconery** [comment]
Couldn't help myself...

**Comment by xivSolutions** [comment]
Lol love it.

**Comment by xivSolutions** [comment]
Did you struggle with the choice between "luke_file_walker" and "file_walk_with_me"?

**Comment by robconery** [comment]
Lol... Btw I screwed up; the function assignment needs to happen in the walker file. Try and execute the deep query, it won't work. Wanna fix?

Just move the function bind from index into Luke

**Comment by xivSolutions** [comment]
I can after work. Grrr. :-(

**Comment by robconery** [comment]
I blew it... fixing again

**Comment by robconery** [comment]
OK fixed it... too late!

**Comment by xivSolutions** [comment]
I figured that would happen :)

Is it Friday yet?
