### ISSUE TITLE
ECONNREFUSED on connectSync

### ISSUE THREAD

**Issue by scrudge** [robconery/massive-js#210]
I get the following error:
```
/home/lowen/src/recall-service/node_modules/massive/node_modules/deasync/index.js:38
			throw err;
			      ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
    at Function.module.exports.loopWhile (./node_modules/massive/node_modules/deasync/index.js:64:21)
    at Object.connectSync (./node_modules/massive/node_modules/deasync/index.js:36:18)
    at Object.<anonymous> (./app.js:5:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I can connect to the db with "psql -d phoenix"

Here's my app.js

```
var express = require('express')
var app = express()

var massive = require("massive")
var connectionString = "postgres://localhost/phoenix"
var massiveInstance = massive.connectSync({connectionString : connectionString})

app.set('db', massiveInstance)

var bodyParser = require('body-parser')
var port = process.env.PORT || 3000
var cors = require('cors');

app.use(cors())
app.use(express.static(__dirname + '/public'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: true}))
app.use(require('./controllers'))

app.listen(port, function() {
  console.log('Listening on port ' + port)
})
```

**Comment by xivSolutions** [comment]
You haven't specified a username in your connection string. In most cases (and depending on how you configured your Postgres install and users, you should be able to:

```js
var connectionString = "postgres://postgres@localhost/phoenix"
```

You may need to specify an actual user + password:
```js
var connectionString = "postgres://someuser:somepassword@localhost/phoenix"
```

**Comment by scrudge** [comment]
Thanks, I was using peer authentication, so I didn't think it was needed.  I switched to password auth and added username and password to the connection string.  I still get the exact same error.

**Comment by xivSolutions** [comment]
Hmmm....platform? Postgres version?

Also, maybe try it using the more standard async call? There have been some issues with the deasync lib. We will likely be pulling that out into a separate lib in the future.

**Comment by scrudge** [comment]
I'm running Debian Jessie, Postgres version:
```
phoenix=> SELECT version();
                                            version                                            
-----------------------------------------------------------------------------------------------
 PostgreSQL 9.4.6 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
```

I tried going async like : 
```
var massive = require("massive")
var connectionString = "postgres:/username:password@lowen-desktop/phoenix"

massive.connect({connectionString: connectionString}, function(err, db) {
  console.log(err)
  app.set('db', db)
});
```
But the err object is:
```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

Strange, is can connect with 'psql -d phoenix'

**Comment by scrudge** [comment]
BTW, nothing showing in the postgres log.  Maybe I should specify IP and Port number in the connection string?

**Comment by scrudge** [comment]
OK, I think it's working now, using connectSync.  The trick was to add the port number, I'm guessing that Debian uses a non standard port, 5433?

One more express question if you don't mind.  I'm using app.set like the example.  How to I access "app" in a module, I'm getting "app not defined"

Thanks!

**Comment by robconery** [comment]
All modules in Node are singletons - it's probably better if you just require your db module directly.

**Comment by scrudge** [comment]
Ok, thanks.
