### ISSUE TITLE
Prepare requests

### ISSUE THREAD

**Issue by gjuchault** [robconery/massive-js#211]
Hi.

I plan to use massiveJS for one of my projects but I can't find anything on this repo about preparing statements.

There are params, but are they in any way prepared/escaped/sanitized by ;assive or one of its dependencies ?

Thanks

**Comment by xivSolutions** [comment]
Params are parsed and submitted per [brianc's Node-Postgres driver](https://github.com/brianc/node-postgres/wiki/Prepared-Statements), which, as far as I understand, adheres to Postgres query parameter requirements. See specifically the section on [Parameterized Queries](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#parameterized-queries)

**Comment by gjuchault** [comment]
Okay, thank you :)
