### ISSUE TITLE
Querying WHERE table.attribute IN [array]

### ISSUE THREAD

**Issue by aray12** [robconery/massive-js#216]
I don't know if this is already possible (I tried and got a syntax error) but it would be great if you could pass an array as a parameters to SQL files so you could do something similar to the following

`where_in.sql`
```SQL
SELECT * 
FROM table
WHERE table.table_id IN $1;
```

Then it would be called like this:

```javascript
var table_id_list = [1,2,3,4,5];

db.where_in([table_id_list], (err, res) => {
  // Do what you need to do...
});
```

**Comment by dmfay** [comment]
You can parameterize an IN list of a fixed length if you write your statement as `...WHERE table.table_id IN ($1, $2, $3);`, but you probably want to be able to pass in as few or as many items as you want at any given time. I don't think the parameterization engine allows for that, but fortunately there's an only-slightly-hacky workaround using array parameters:

```sql
SELECT * FROM products WHERE id = ANY($1);
```

```javascript
db.someProducts([[1, 2]], function(err,products){
    assert.ifError(err);
    var p1 = products[0];
    var p2 = products[1];
    assert.equal("Product 1", p1.name);
    assert.equal("Product 2", p2.name);
    done();
});
```

Note the nested array -- functions and query files take in arguments as an array already, so the payload has to account for that.

**Comment by aray12** [comment]
@dmfay thanks for the response. The advantage of this would be the fact that number of arguments would be dynamic, but your second recommendation is exactly what I was looking for. Just curious, why would you consider this "only-slightly-hacky"? Looking at the documentation I can't seem to determine any serious differences in behavior between ANY and IN.

**Comment by dmfay** [comment]
I called it hacky because it's achieving the same result as the standard form `x IN (y, z)` in a non-standard way -- which, however effective it might be (and it is!), is imo definitionally a hack. You're right there are no major differences, but [here's](http://dba.stackexchange.com/questions/125413/index-not-used-with-any-but-used-with-in) one example where the finer points might trip someone up.

**Comment by aray12** [comment]
@dmfay understood. Again thanks for the quick response.
