### ISSUE TITLE
Best way to do an updated_at column?

### ISSUE THREAD

**Issue by cymen** [robconery/massive-js#217]
I realize I could have my code higher up do this but before I do that, is there an easy/best way to do an `updated_at` column? It looks like `created_at` is easy with something like:

`created_at timestamp default current_timestamp`

But `updated_at` examples for psql typically use a trigger like this example:

http://www.revsys.com/blog/2006/aug/04/automatically-updating-a-timestamp-column-in-postgresql/

I'll go forward doing it at a higher level (setting `update_at` myself) but just curious if this is a concern massive-js might address or if it should stay higher up.

**Comment by robconery** [comment]
Massive does do this for document stuff, but no we don't do it for regular tables. Make sure you use `timestamptz` if you need timezone correlations - and yes a trigger is a good idea :).

**Comment by cymen** [comment]
Excellent -- thanks, I'll look into `timestampz` too :).
