### ISSUE TITLE
Move to promises

### ISSUE THREAD

**Issue by aray12** [robconery/massive-js#226]
I was just wondering if there is any internal conversations going about potentially moving to a promised-based architecture? Or providing both a callback and promise-based API?

**Comment by xivSolutions** [comment]
This has been asked about a few times - and at this point, we will not be adding promises directly. 

See the discussion below:

https://github.com/robconery/massive-js/issues/37

https://github.com/robconery/massive-js/issues/81

https://github.com/robconery/massive-js/issues/142

**Comment by aray12** [comment]
I probably should have done a quick search... I'm a fan personally but I will continue to promisify for now

**Comment by robconery** [comment]
I'm actually open to moving to promises in v3 - just need some help.
