### ISSUE TITLE
Question using jsonb.

### ISSUE THREAD

**Issue by thejones** [robconery/massive-js#229]
Is it possible to save or query jsonb if the field is not called "body" and still use the findDoc, saveDoc methods? 

If I had a "profile" for example. 
```
create table doggies(
  id serial primary key,
  body jsonb not null,
  profile jsonb not null,
  search tsvector,
  created_at timestamptz default now()
);
create index idx_doggies on doggies using GIN(body jsonb_path_ops); 
create index idx_doggies on doggies using GIN(profile jsonb_path_ops); 
create index idx_doggies_search on doggies using GIN(search); 
```

Can I save into it using saveDoc? 
```
//This goes into body
db.doggies.saveDoc({name : "Stinky"}, function(err,doc){
  //hello Stinky!
});
```

Something like this? 
```
db.doggies.saveDoc('profile', {name : "Stinky"}, function(err,doc){
  //hello Stinky!
});
```

**Comment by robconery** [comment]
Not really - the whole idea with saveDoc etc is that you don't think about the abstraction. If you need something else, perhaps roll your own and query as normal?

**Comment by dmfay** [comment]
Also -- document tables are still tables, and you can use the standard find, insert, update, and other functions with a document table just fine if you want to build on top of it.

**Comment by thejones** [comment]
Rock on!!
