### ISSUE TITLE
request for findOneDoc -- just like findOne, but for documents

### ISSUE THREAD

**Issue by habermeier** [robconery/massive-js#234]
Not a big deal, but I just found myself writing this code:

        let masterDocs = await table.findDocAsync( { meta : { type: masterDocType } } );
        let masterDoc = masterDocs[0];

Which is a bit silly... so might be nice to have findOneDoc.

(please note -- above includes by async wrapper using typescript)... but you get my point.

**Comment by robconery** [comment]
I do believe the `options` work on this one if you pass `{single: true}`

**Comment by dmfay** [comment]
Just added documentation and a testcase proving it, but yes, `single` works in 2.2.0.
