### ISSUE TITLE
saveDoc deletes the primary key from the document passed in

### ISSUE THREAD

**Issue by dmfay** [robconery/massive-js#236]
With predictable ramifications if you have an automated system that can execute multiple steps on a document and need to persist it after each one! :)

Should be an easy fix, I'll try to get to it soon.

**Comment by robconery** [comment]
Hmmm - the idea was to prevent some duplication; I suppose we can have it in both places - looks like the tests still work so I guess it's OK :).

**Comment by dmfay** [comment]
oh, that part works exactly as it used to -- the body saved to the database doesn't have the pk value (`_.omit(args, pkName)` returns an altered copy). I needed it to stop modifying the _original_ document I passed in since my process can call `saveDoc` with the same object multiple times.
