### ISSUE TITLE
Add a note to scripts function that the file names must end with '.sql' to be considered

### ISSUE THREAD

**Issue by habermeier** [robconery/massive-js#246]
It's probably obvious to everyone else, but it'd be great if the documentation mentions that files in the 'db' directory need to end with .sql for massive-js to pull the file in.  It's implied with 

> Each function will have the same name as the script file, sans extension.

In the documentation: https://massive-js.readthedocs.io/en/latest/functions/  

It makes a ton of sense that it should go into a .sql file.  I actually renamed my file initially to remove the extension.  Silly me.

**Comment by robconery** [comment]
Makes sense :). If you wanted credit for the PR that would be great!

**Comment by dmfay** [comment]
PR made it in a while back.
