### ISSUE TITLE
Can I make a LIKE query using Find?

### ISSUE THREAD

**Issue by andrerpena** [robconery/massive-js#251]
First off. Thanks for this lib. I like it better than Bookshelf and Sequelize.

Is there a way to create a LIKE query using Find? Something like thi?

    db.contacts.find({'email like': 'gussie%'}, (e,r) => {});

 Thank you.

**Comment by robconery** [comment]
I think you can just...

```
db.contacts.where("email like $1", ["rob"], (e,r) => {});
```

or

```
db.contacts.find("email like $1", ["rob"], (e,r) => {});
```

**Comment by andrerpena** [comment]
Oh I see. I just thought there was a 'like' operator for Find because there
is a greater than and lesser than.

Thank you.

BTW, love your pluralsight courses.
Em 14 de mai de 2016 12:55, "Rob Conery" <notifications@github.com>
escreveu:

**Comment by dmfay** [comment]
It's kind of a glaring omission imo, so I spent some time over the weekend seeing what I could do. Postgres has a bunch of neat expanded pattern-matching operators above and beyond just `LIKE` and `NOT LIKE` (case-insensitive `ILIKE`, regexes, weird mishmash of SQL pattern-matching and regex) and it's a shame to leave those out of the criteria finders. It's not quite ready yet but I'll probably finish it up and roll it in sometime this week.

**Comment by andrerpena** [comment]
@dmfay. That makes sense... Thank you for that.

**Comment by xivSolutions** [comment]
👍

**Comment by robconery** [comment]
Woohoo!

**Comment by briancray** [comment]
Awesome, I was just trying to use ~* operator on body::text
