### ISSUE TITLE
Functions as column when updating [Bug or feature?]

### ISSUE THREAD

**Issue by lfreneda** [robconery/massive-js#260]
Hello folks, since last release (>= 2.3.0) I'm getting the following error:

:no_entry_sign:  ```column \"reportAsProblem\" of relation \"activities\" does not exist```

In fact, I have coffee class that looks like this:

```
class Activity
 constructor: (@id, @description, ..)
 reportAsProblem: () ->
   # change state
```

When saving with ```db.activities.save```, Massive is trying to find a column in activities table named ```reportAsProblem```.

Previous versions it was ignored and everything works as expected :angel: 

The question is:

Is a new massive behavior/feature to save "calculations fields" or something like this? 
If so, is possible to ignore it somehow?

Or is really a bug?

**Comment by robconery** [comment]
Can you show me the JS instead of CoffeeScript?

**Comment by lfreneda** [comment]
@robconery sure! Wow, so fast D: r u the Flash?

![Rob as Flash](http://cdn.movieweb.com/img.albums/TVufx5U58nxSxB_2_300.jpg)

Since coffeescript is

```
class Activity
  constructor: (params) ->
    binder @, properties, params

  reportAsProblem: (problemDescription) ->
    @status = ActivityStatus.reported
    @problemDescription = problemDescription

module.exports = Activity
``` 

it will be converted to:

```
var Activity;

Activity = (function() {
  function Activity(params) {
    binder(this, properties, params);
  }

  Activity.prototype.reportAsProblem = function(problemDescription) {
    this.status = ActivityStatus.reported;
    return this.problemDescription = problemDescription;
  };

  return Activity;

})();

module.exports = Activity;
```

Thanks you a lot

**Comment by robconery** [comment]
OK, now you show me the code that's failing with the exception etc...

**Comment by lfreneda** [comment]
Just found out that the problem is when **updating** 

I created a repository https://github.com/lfreneda/massive-js-issue-260 to replicating the error

code failing: https://github.com/lfreneda/massive-js-issue-260/blob/master/src/index.coffee

```
{ Error: column "reportAsProblem" of relation "activities" does not exist
    at DB.query (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/massive/lib/runner.js:22:11)
    at Table.update (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/massive/lib/table.js:100:11)
    at Table.save (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/massive/lib/table.js:121:10)
    at Object.next (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/src/index.js:28:28)
    at .callback (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/massive/lib/runner.js:67:14)
    at Query.handleReadyForQuery (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/pg/lib/query.js:89:10)
    at .<anonymous> (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at Socket.<anonymous> (/home/ryuk/lfreneda/work/issues/massive-js-issue-260/node_modules/pg/lib/connection.js:109:12)
  message: 'column "reportAsProblem" of relation "activities" does not exist',
  code: '42703',
  detail: undefined,
  length: 127,
  severity: 'ERROR',
  hint: undefined,
  position: '60',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'analyze.c',
  line: '1997',
  routine: 'transformUpdateStmt' }
```

**Comment by robconery** [comment]
Weird. Looks like the serializer is turning this function into a property. Not sure what to make of it.

Also - you're using Massive like an ORM, I might suggest being explicit with what you want to save. We do partial updates, so if you only want to update a few columns, perhaps specify them.

**Comment by lfreneda** [comment]
@robconery, Since insert is working as expected, I might have a clue..

object properties on insert are retrieved with undercore keys ```_.keys(object)```
object properties on update are retrieved with underscore omit ```_.omit(fields, pkName)```

it was changed on this commit:
https://github.com/robconery/massive-js/commit/591c430c66799e0a93c545ef2340c1888f0980b8

**Comment by lfreneda** [comment]
Can I implement something to fix it?

**Comment by robconery** [comment]
Sure - we just need to be sure we omit the PK as an update field.

**Comment by lfreneda** [comment]
Got it, give me some minutes haha

**Comment by lfreneda** [comment]
What u think? https://github.com/robconery/massive-js/pull/261
