### ISSUE TITLE
db.run to CREATE TABLE

### ISSUE THREAD

**Issue by swinston100** [robconery/massive-js#262]
Hi

I would like to create a table if it doesn't exist. My code is not working.

```js
function(db, data, done){

  db.run("CREATE TABLE IF NOT EXISTS revenue(id serial primary key, \"Date\" integer, \"Account Name\" varchar(255) not null, \"Total Sold Imps\" integer, \"Imps Bought\" integer, \"Publisher Rev\" numeric)",
  function(err, res){
    if(err){  console.log("error: " + err); }
    else{
      db.revenue.insert(data, function (err, res) {
        if(err){  console.log("error: " +err); }
        done();
      });
    }
  });

}

```

If the table does not exist it creates it and then exits with:

> TypeError: Cannot read property 'insert' of undefined

The second time around (or if the table does exist) it works perfectly.

I also tried using `async.series` with the same results.

```js
  async.series([createTable, saveTable], function(err,results){
    if(err){  console.log("error: " + err); }
    done();
  });
  
  function createTable(cb){
    db.run("CREATE TABLE IF NOT EXISTS revenue(id serial primary key, \"Date\" integer, \"Account Name\" varchar(255) not null, \"Total Sold Imps\" integer, \"Imps Bought\" integer, \"Publisher Rev\" numeric)",
    function(err, res){
      if(err){  console.log("error: " + err); }
      else cb();
    });
  }
  
  function saveTable(cb)  {
    db.revenue.save(data, function (err, res) {
      if(err){  console.log("error: " +err); }
      cb();
    });
  }

```

Is there anyway to asynchronously create a table and then use it? Thanks!

**Comment by swinston100** [comment]
I also tried

```js
  db.runSync("CREATE TABLE IF NOT EXISTS revenue(id serial primary key, \"Date\" integer, \"Account Name\" varchar(255) not null, \"Total Sold Imps\" integer, \"Imps Bought\" integer, \"Publisher Rev\" numeric)");
  db.revenue.insert(data, function (err, res) {
    if(err){  console.log("error: " +err); }
    done();
  });
```

But had the same results.

**Comment by dmfay** [comment]
Massive only scans for db objects on startup, so if you alter your schema while it's running you'll need to reconnect to your database (with the exception of document tables as mentioned in #259 ). Doing that on command shouldn't cause any major problems since Node is single-threaded, but unless you have some scenario that absolutely requires modifying your schema on the fly it's better to have it all ready before you connect Massive in the first place so you're only incurring the startup cost once.

**Comment by swinston100** [comment]
@dmfay - many thanks

Any idea how to disconnect using db.run()? I've tried to connect to another database, \q.. even

```js
  db.runSync("select pg_terminate_backend(pid) from pg_stat_activity where datname= 'Excel'")
```
Thanks!

**Comment by xivSolutions** [comment]
@swinston100 - I don't think you want to terminate the connection that way. I you *really need* to reload the schema, you should look into ways, in the context of your application, to just re-initialize the `db` variable by calling `connect` again, which is what causes the database schema stuff to be loaded. 

I am wondering why you need to create a table such as `Account` at runtime? Are you certain this issue is not related to a need to re-examine your database architecture? I strongly suspect you might want to consider how it is you are persisting `Account` records. Can you provide some detail as to why you want to do this?

**Comment by swinston100** [comment]
Hi @xivSolutions 

i tried to re-initialize the db variable

both with simply 

```js
var massiveInstance = massive.connectSync({connectionString : Database.connectionString});
app.set('db', massiveInstance);
var massiveDB = app.get('db');
//create table
massiveInstance = massive.connectSync({connectionString : Database.connectionString});
Database.writeDB(massiveDB, excelData, done);
```

and

```js
var massiveInstance = massive.connectSync({connectionString : Database.connectionString});
app.set('db', massiveInstance);
var massiveDB = app.get('db');
//create table
var kassiveInstance = massive.connectSync({connectionString : Database.connectionString});
app.set('dab', kassiveInstance);
var kassiveDB = app.get('dab');
Database.writeDB(kassiveDB, excelData, done);
```

But neither reloaded the schema.

The database schema is decided at runtime as it is based on an excel spreadsheet given by a user.

**Comment by xivSolutions** [comment]
You might take a look at the `/test/helpers/index.js` file for an example of re-setting the Db. 

Note, you will need to watch mixing your sync/async calls here - if you make an async call to do your table creates, you will need to wrap your call to reset the Db in a callback that gets executed when the table creates are done. 

In this case, you might want to factor out your loading of the Db and setting of the Express variable into a discrete method. Also, I would probably go all-in with async calls/callbacks here. First off, we will be deprecating the `deasync` stuff in the near future, and also it will save you from possible situations where your code execution cooks right on past an async call to create tables, and executes the next (sync) call to load the Db, when in fact the table create bits have likely not even executed yet.

**Comment by swinston100** [comment]
@xivSolutions  - thanks. I treid resetting in the same manner as index.js but with no luck.
I was making sure with callacks that insert was only happening after the rest which in turn only happened after the create.

I have found a solution where I use pg to create the table

```js
var pg = require("pg");
pg.connect("postgres://postgres:password@localhost/excel", function(err, client, done){
  client.query("CREATE TABLE IF NOT EXISTS revenue(id serial primary key, \"Date\" integer, \"Account Name\" varchar(255) not null, \"Total Sold Imps\" integer, \"Imps Bought\" integer, \"Publisher Rev\" numeric)");
  done()
});
```

And only after that do I load massive.

Ideally I would have loved to just stick to massive but this now works well.
Thanks for your help! Really appreciated!

**Comment by xivSolutions** [comment]
Great - glad you solved it :-)
