### ISSUE TITLE
crashing after upgrading to 2.3.0

### ISSUE THREAD

**Issue by dmitryame** [robconery/massive-js#266]
It used to work fine in 2.1.0, but after upgrade to 2.3.0, the following stack trace happens and then node crashes:

```
  Error: column "load" of relation "checkins" does not exist
      at DB.query (/Users/dmitry/hacks/tlog/TLogServer/node_modules/massive/lib/runner.js:22:11)
      at Table.update (/Users/dmitry/hacks/tlog/TLogServer/node_modules/massive/lib/table.js:100:11)
      at null.updateSync (/Users/dmitry/hacks/tlog/TLogServer/node_modules/massive/node_modules/deasync/index.js:43:7)
      at Checkin.update (/Users/dmitry/hacks/tlog/TLogServer/models/checkin.js:52:22)
      at Object.<anonymous> (/Users/dmitry/hacks/tlog/TLogServer/routes/checkins.js:150:17)
      at next (native)
      at Object.dispatch (/Users/dmitry/hacks/tlog/TLogServer/node_modules/koa-router/lib/router.js:336:14)
      at next (native)
      at Object.dispatch (/Users/dmitry/hacks/tlog/TLogServer/node_modules/koa-router/lib/router.js:336:14)
      at next (native)


  Error: Parse Error
      at Error (native)
      at Socket.socketOnEnd (_http_server.js:416:22)
      at emitNone (events.js:72:20)
      at Socket.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:913:12)
      at nextTickCallbackWith2Args (node.js:442:9)
      at process._tickDomainCallback (node.js:397:17)
      at Function.module.exports.loopWhile (/Users/dmitry/hacks/tlog/TLogServer/node_modules/massive/node_modules/deasync/index.js:71:11)
      at null.findOneSync (/Users/dmitry/hacks/tlog/TLogServer/node_modules/massive/node_modules/deasync/index.js:44:19)
      at Subcontractor.load (/Users/dmitry/hacks/tlog/TLogServer/models/subcontractor.js:16:46)
./rundev.sh: line 9: 12396 Segmentation fault: 11  node app.js

```

Here is the contents of the   checkin.js around line 52:
```
Checkin.prototype.update = function () {
  return db.checkins.updateSync(this);
}
```

And the line 16 of subcontractor.js:
`  var foundSubcontractor = db.subcontractors.findOneSync({id:this.id});
`

Please help

**Comment by xivSolutions** [comment]
I suspect you experiencing the weirdness with the deasync library. 

you are using synchronous method calls, which rely on deasync. Unless you are doign something specific which requires the sync call, I strongly recommend you ditch the synchronous stuff. 

In fact, we will be removing all that in an upcoming rev, as there are too many issues with deasync, and it seems to be encouraging people to try to use Node in a synchronous manner where it really, really shouldn't be.

**Comment by dmitryame** [comment]
OK then,
I do not mind switching, and I'm typically a fast learner, through, with node I find it's a bit overwhelming, with all the callbacks, promisses, generator functions, KOA, express etc.... ?
Is there a decent documentation which explains how to use massive the "right way"?

**Comment by dmitryame** [comment]
Just tried switching to callback, here is error I'm getting inside the callback function:

```
{ [Error: column "load" of relation "checkins" does not exist]
  message: 'column "load" of relation "checkins" does not exist',
  code: '42703',
  detail: undefined,
  length: 121,
  severity: 'ERROR',
  hint: undefined,
  position: '115',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'analyze.c',
  line: '2163',
  routine: 'transformUpdateTargetList' }

```

I really believe this has nothing to do with the synch stuff since I was getting the same exact error.

**Comment by xivSolutions** [comment]
The read me gives you the basics, and there's a [link to some](http://massive-js.readthedocs.org/en/latest/) docs as well. Fortunately, Massive keeps it pretty simple. For the moment it is callback-based, not promises, although we will be moving to promises and a 100% ES2015 story in the next version. 

Don't be afraid to ask questions. I can see how the sync stuff might seem tempting, but really, when in Node, use Callbacks (or promises as the case may be, but Massive doesn't directly support that yet).

**Comment by xivSolutions** [comment]
Ah, ok. Hang on.

**Comment by dmitryame** [comment]
BTW, I do not have column name "load" in any of my tables

**Comment by dmitryame** [comment]
Hey, thank you for your help -- I really will try the asycnh stuff -- it's very cool and I'm all for benefitting from doing it the asynch way.

**Comment by xivSolutions** [comment]
Right. Do you have your code in a repo you can link to? Looks like there's something going on, but I have no way to know without seeing a larger code context.

**Comment by dmitryame** [comment]
I can share the code with you privately, hangon.

**Comment by xivSolutions** [comment]
Ok, can you point me to the code file where the issue is occuring? Where is the call where the problem arises?

**Comment by dmitryame** [comment]
models/checkin.js:59

**Comment by xivSolutions** [comment]
Shit, I guess that was already stated in the output above. Mybad. Hang on then...

**Comment by xivSolutions** [comment]
Ah. ok. 

You are doing THIS:

```js
    var checkin =
      new Checkin({
        email: email,
        user_id: user_id,
        checked_in_at: checked_in_at,
        duration: duration,
        action_code_id: action_code_id
      });
    checkin.save();
});
```

But you need to pass the object to be saved into `db.save(yourObject)` (`db` or whatever you are using to hold your massive variable. 

See the readme file, where the example is:

```js
//no PK does an INSERT
db.users.save({email : "new@example.com"}, function(err,inserted){
  //the new record with the ID
});
```

So in your case, you would want to do something like:
```js
    var checkin =
      new Checkin({
        email: email,
        user_id: user_id,
        checked_in_at: checked_in_at,
        duration: duration,
        action_code_id: action_code_id
      });
    checkin.save(checkin);
```

BUT, you need to have your massive instance available first. 

See the test files, the readme, and maybe experiment a little. Massive is not an ORM in the familiar sense. 

In particular, for CRUD ops, see the `table_spec.js` file:

https://github.com/robconery/massive-js/blob/master/test/table_spec.js

**Comment by dmitryame** [comment]
I was using slightly different pattern, but I think it should work too.
Instead of passing the object into the method, the method accesses the properties of the object it's called on via this. So, first set the properties of the object, then call method on it which will have access to all the previously set properties. That's why I'm calling db.checkins.save(this,.... inside the checkin.save() method. 
I will try to follow your suggestion and pass the object explicitly, though, not sure if it's gonna help -- will let you know shortly.

**Comment by dmitryame** [comment]
btw, it was all working fine in 2.1.0, but in 2.3.0 it shows this misterious error:
`column "load" of relation "checkins" does not exist`
I do realize that massive is not an OR tool, and I acutlaly love it's simplicity, elegancy and power (but mostly simplicity). Though, It's really strange where does the "load" column pops from, specially that it was working before the upgrade (and no code was changed on my end).

**Comment by xivSolutions** [comment]
Ah. Missed that bit. Ok. Seems like we've seen this recently as well. 

You have properties on your object which Massive is then trying to map to database columns. Specifically, your `Checkin.prototype.load` property. 

This is the donwside of the way you are doing it, although seems like recently @dmfay was assisting someone with a similar issue.

**Comment by xivSolutions** [comment]
See [this issue](https://github.com/robconery/massive-js/issues/260) and specifically the resolution [HERE](https://github.com/robconery/massive-js/commit/ca04d3cbd67f50892ae2989700dd8776b5a56420)

**Comment by dmitryame** [comment]
this fixed it, thank you!

**Comment by dmitryame** [comment]
just for kicks, any eta on when the next version supporting ES2015 will be out? Does not have to be precise, are we talking few days, weeks, months?

**Comment by xivSolutions** [comment]
Probably a few months anyway. But you never know!

**Comment by dmitryame** [comment]
cool, thanks

**Comment by dmitryame** [comment]
So, I'm trying to figure out how to correctly thunkify massive functions:

```
Subcontractor.prototype.load = function () {
  var findOne = thunkify(db.subcontractors.findOne);

  co(function *() {
    try {
        var res = yield findOne({id:this.id});
    } catch (err) {
        console.log(err);
      }
      console.log(res);
    })();
}

```

The code fails with the following error (this is printed from inside the catch block):
`[TypeError: this.find is not a function]
`
I know, I'm doing doing anything meaningful with the results yet, I just want to print the res out for now.
Any hints what am I doing wrong?

**Comment by dmitryame** [comment]
btw, not sure if this question will get noticed since the issue is closed, so I just moved this question to http://stackoverflow.com/questions/37669469/how-to-correctly-thunkify-massive-js

**Comment by xivSolutions** [comment]
You are having the same problem we discussed earlier. The error message should be telling you loads here. `find` is a function defined on the table in massive. `findOne` calls `find`. 

You are bolting Massive functions onto your objects, and massive is then trying to translate them into columns for data access.

**Comment by dmitryame** [comment]
Not really, I'm not bolting Massive functions to my objects

` var findOne = thunkify(db.subcontractors.findOne);`

and then explicitly passing just an id value into the findOne of db.subcontractors:

`var res = yield findOne({id:this.id});`

**Comment by xivSolutions** [comment]
You likely need to also thunkify the `find` function, and others within Massive. 

I strongly recommend you lean into the callback style of programming, or MAYBE try the using bluebird w/PromisifyAll if you are dead set on trying to avoid callbacks. 

But seriously, callbacks are an innate part of how JS works.

**Comment by xivSolutions** [comment]
Yeah, I saw that, and changed my response :)

**Comment by dmitryame** [comment]
I would love to do the right thing and use callbacks, however, I'm using KOA with generators and trying to figure out how to use massive with KOA, and all suggestions that I come across on the web lean towards thunkify with co. I'm open to doing it differently, if someone can share a code sample how to use massive with KOA.

**Comment by lfreneda** [comment]
Any idea when a new release will be publish to npm?

**Comment by robconery** [comment]
Just now! We're revved to 2.4...

**Comment by lfreneda** [comment]
<3
