### ISSUE TITLE
FindDoc: No result without where condition

### ISSUE THREAD

**Issue by MarcelCremer** [robconery/massive-js#267]
Hello everyone,

when I try to do something like

`db.table.findDoc({}, function(error, entry){
console.log(entry);
});`

I won't get any results. I tried to get the latest document by id, so my full code would be something like

`db.table.findDoc({},{order: "id desc", limit: 1}, function(error, entry){
console.log(entry);
});`

Is this intended?

I used

`db.table.find({},{order: "id desc", limit: 1}, function(error, entry){
console.log(entry[0].body);
});`
now as a workaround, but wanted to make sure that it's per design and not a bug.

Best Regards
Marcel
P.S.: Great Work! It's so much fun to work with massive.js :)

**Comment by dmfay** [comment]
That's a bug!
