### ISSUE TITLE
Is it possible to run a migration using a variable name for the file in the db directory

### ISSUE THREAD

**Issue by hypexr** [robconery/massive-js#270]
The files in my db/queries directory are not known at run time.  I have a variable holds the name.

Say the filename is:
db/myquery.sql

If I knew the filename I could write
```
db.myquery(function(error) {
});
```

Is there a way for me to do something like:
```
db.execute(nameOfFile, function(error) {
});
```

If not should I read the file in as a string and use "run"?

**Comment by robconery** [comment]
Have you tried `db["myquery"](function...`"

**Comment by hypexr** [comment]
Just tried it and I get:

`Uncaught TypeError: db[sqlScriptFileName] is not a function`

**Comment by xivSolutions** [comment]
@hypexr - Yeah, if the files are not present when Massive loads at application start, they won;t be available as functions (at least, in the current incarnation of Massive). 

For now you would need to do as you suggest, and read the text, and execute using `run`.

**Comment by hypexr** [comment]
@xivSolutions The files are actually available at application start, the name of which one to run is provided at runtime (these sql files are for database migrations and don't take special arguments or anything). Does that mean that it may be possible, without some funky eval implementation?

**Comment by hypexr** [comment]
Nevermind, the db[variable] works.  I had just forgot to set the scripts directory in the connect.  Thanks!
