### ISSUE TITLE
How do I manually close a connection?

### ISSUE THREAD

**Issue by andrerpena** [robconery/massive-js#277]
I'm using Massive together with Knex, because Knex is better for manipulating my DB schema.
The problem is: When Knex tries to delete a database, it can't because it's being used by Massive. 

How can I manually close a Massive connection?

**Comment by robconery** [comment]
You can use `db.end()` to release the connection, but we use a connection pool, as does Knex (probably) so it's not really being released. 

Can't really help you otherwise.

**Comment by andrerpena** [comment]
connection.end() actually solved my problem with Knex. Thank you Rob.

On Fri, Jun 24, 2016 at 6:08 PM, Rob Conery <notifications@github.com>
wrote:

> Closed #277 <https://github.com/robconery/massive-js/issues/277>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/robconery/massive-js/issues/277#event-703707753>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABghdQ6Oz1urGMo5QcaNpvYDx_pWIgERks5qPEdVgaJpZM4I-Bfb>
> .
>



-- 
André Rodrigues Pena

**Comment by andrerpena** [comment]
Just for the science.. If I never use massive to query in parallel,
connection.end() works great. Otherwise, it does not. Thank you.

On Sat, Jun 25, 2016 at 6:40 AM, André Pena <andrerpena@gmail.com> wrote:

> connection.end() actually solved my problem with Knex. Thank you Rob.
>
> On Fri, Jun 24, 2016 at 6:08 PM, Rob Conery <notifications@github.com>
> wrote:
>
>> Closed #277 <https://github.com/robconery/massive-js/issues/277>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/robconery/massive-js/issues/277#event-703707753>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/ABghdQ6Oz1urGMo5QcaNpvYDx_pWIgERks5qPEdVgaJpZM4I-Bfb>
>> .
>>
>
>
>
> --
> André Rodrigues Pena
>



-- 
André Rodrigues Pena
