### ISSUE TITLE
Using massive.js to import from `pg_dump`

### ISSUE THREAD

**Issue by rarkins** [robconery/massive-js#279]
I understand that that this is not its primary purpose, but can MassiveJS be used to simply "execute" SQL files, essentially as a replacement for `psql`?

I currently have a 100MB+ `.sql` file generated by `pg_dump`, which needs to be imported into postgresql. Today I do this via a bash script invoking `psql`, but it would make my architecture much cleaner if I could do it in Javascript.

**Comment by xivSolutions** [comment]
Yes. if you mean "can I execute the output from a pg_dump as a SQL script, certainly.  In fact, if you take a look in the `test/helpers/index` file [HERE](https://github.com/robconery/massive-js/blob/master/test/helpers/index.js) you will see that our tests load up a file named `schema` in the `scriptsDir` and then execute it as a JS function. While the `schema` file is not output from pg_dump, you will see an example of using a script file to create tables and load data.

Note, however, that you need to engage in some trickery if you want to execute the actual database create bits. To do that, you have to connect initially to another database on the Postgres instance (the `postgres` database works), then execute the database creation stuff, and then connect to the newly created db and run your table/object creates, and populate with data. 

I had something like that put together at some point, but the details are lost on my at the moment. Wasn't horribly difficult to do, but did have to experiment a little. 

If you are asking whether you can execute psql commands, not directly, but you could experiment with adding some code to your application to do so - again, I don't think that's overly difficult, it's just not part of MassiveJs at the moment (although I think it might be a handy addition to v3!)

See [HERE](http://stackoverflow.com/questions/20643470/execute-a-command-line-binary-with-node-js) for a quick example. I have not tried this myself, but psql is, in fact, a command-line binary, so...

**Comment by robconery** [comment]
While this will work, I need to throw some caution here. `psql` is very capable and if you need to execute it from JS I would push you to experiment with `System.cmd` and pipe a command out to the shell.

100Mb is quite large and will probably slow your entire app down as Massive will read that file and load it into memory... and that's your app memory... which could cause some problems depending on your environment.

**Comment by rarkins** [comment]
Thanks @xivSolutions and @robconery for your suggestions. Because I'll need this to function perfectly as part of production deploy, I decided I'd better stick with binary `psql`. The reason I had hoped to avoid that option was that there doesn't appear to be a way to get it without the entire `postgresql` install.
