### ISSUE TITLE
Mapping the result set of a JOIN query?

### ISSUE THREAD

**Issue by igrayson** [robconery/massive-js#283]
From https://github.com/robconery/massive-js/issues/263, I gather that massive doesn't have the ability to directly query multiple tables.

However, if I'm willing to write the SQL myself, a real benefit massive could grant me is mapping the result set into a nested object. In particular, for 1:many relationships.

As I understand it (please confirm?) massive would only provide me with an array of plain objects, each representing a single row in the result set.

What I'm after is a mapper able to parse the join so that the returned objects are nested in 1:n relationships, reflecting the rows in the joined.

Is massive capable of doing this? If not, is this a goal for the massive project? And, are the collaborators aware of any other (mature) javascript projects which can provide this? I'm striving to avoid using sequelize and its complex abstractions.

**Comment by robconery** [comment]
No, it can't and no, it's not a goal. What you're describing is what an ORM does, and this isn't an ORM.

That said - the document stuff (JSONB) is exactly what you need. Or you could write your own SQL file and use a function to serialize results to JSON, giving you back what you want. I think I did something like that and I can try to find it if you're up for some SQL fun.

**Comment by xivSolutions** [comment]
Like Rob said - Massive doesn't do that type of mapping directly, but you can definitely use Postgres' JSON type and Array/aggregate functions to impose a document structure on relational data, and then return the JSON object the way you describe. 

You can find the really [basic details in a blog post](http://johnatten.com/2015/04/22/use-postgres-json-type-and-aggregate-functions-to-map-relational-data-to-json/) I did a ways back, and I know [Rob has also written about this approach](http://rob.conery.io/2014/10/31/pulling-documents-from-a-relational-query-in-postgres/).

You can definitely create this type of query as a SQL file as Rob says, and then just call it as a function in Massive.

**Comment by lfreneda** [comment]
@igrayson I wondering, what did you end up doing?

**Comment by dmfay** [comment]
@lfreneda you may find the code I posted in the linked issue useful: https://gist.github.com/dmfay/c4017b8768519679e7948706fc09532e

**Comment by lfreneda** [comment]
@dmfay I'll check it out for sure! thank you

**Comment by igrayson** [comment]
@lfreneda we continue to use Sequelize.
