### ISSUE TITLE
FindDoc: IN with ID does only return first Result

### ISSUE THREAD

**Issue by MarcelCremer** [robconery/massive-js#285]
Hello,

if you execute a query like documented on the README, it will only return the first result:

```
db.my_documents.findDoc({id : [1,3,9]}, function(err,docs){
  //documents with ID 1, 3, and 9
});
```

->Returns only the document with ID 1.

Best Regards
Marcel

**Comment by Sayene** [comment]
Yes, got the same problem with  massive "version": "2.5.0" and postgres 9.6. Any clues for the fix?
