### ISSUE TITLE
Ilike for findDoc

### ISSUE THREAD

**Issue by MarcelCremer** [robconery/massive-js#286]
Hello everyone,

I have a json structure like

```
{
//[...]
   person : {
   attributes : ['user'],
   'firstName' : 'foo',
   'lastName' : 'bar'
   }
}
```

And try to generate a query like:

`SELECT body FROM foobar WHERE body->'person' @> '{"attributes" : ["user"]}' AND (body->'person'->>'firstName') || ' ' || (body->'person'->>'lastName') ilike 'fo%';`

Which is basically, give me all persons who have the attribute user and the Firstname + ' ' + Lastname ilike a term.

My last attempt was something like:
```
var search = {
        person : 
            {'attributes' : ['user'], "firstName ilike" : "Foo%"}
            
    };
    db.foobar.findDoc(search, function (err, rc) {
        console.log(err);
        res.json(rc);
    });
```

However, there I'm stuck because ilike doesn't seem to work for the attributes (complete attribute plus complete term as searchterm does work).

Is this too complex for the framework (which I would understand) or am I missing something in the docs that could've helped me?

Best Regards
Marcel

**Comment by dmfay** [comment]
Massive doesn't build paths out of nested objects (although that would be cool!). You need to use the JSON traversal operators directly eg 
```
db.foobar.findDoc({
    'body#>>{person,firstName} ilike': 'a%'
}, ...)
````

Only the 'as-text' operations `->>` (key/element) and `#>>` (path) are currently supported, which could make matching the array a bit tricky, but try the text field matching out first and see what you get!

**Comment by robconery** [comment]
Fair warning: this query is a time-bomb and I'd strongly urge you to consider using the full text search stuff we have for documents. In order to run this query, Postgres needs to run a full table scan to materialize and then compare the fields.

**Comment by MarcelCremer** [comment]
Hey guys,

thank you for your answers. I really appreciate that you're so friendly in this project - I'll try to contribute something when I'm deeper in PostgreSQL and Massive.

I'll try this out asap. I saw the traversal operation but didn't manage to find out how to use it properly - that example should be a nice start.

@robconery : I also tried to use the fulltext search, but all I've come up with was

```
db.foobar.searchDoc({
  keys : ["person"],
  term : "Marcel"
}, function(err,docs){

});
```
Which matched. All other attempts failed for me (e.g. partial match with term Ma:*). Does the traversal operator work for fulltext searches too?

Have a great day and best Regards
Marcel

**Comment by robconery** [comment]
Interesting problem here. If you need to run partial matches on your document it might not be the best structure for you using Postgres - depending on how you think your table will grow. The index can't be used in this case (although I'm not too sure about that to be honest - I'm 99% sure but since you're changing it to text I think it won't work).

If you have 1000 records, no big deal. 100,000 and the query will slow *everything* down since it will have to materialize each document and then run the compare.

I might suggest denormalizing in this case - possibly using a trigger or something - to put whatever you want to partial match against into it's own column. Then you can index that column and not worry about the future.

**Comment by MarcelCremer** [comment]
Hey robconery,

thank you again for your input. I will start off with the current structure and leave the performance-issue for my future-self :) Until this time, the structure might change one or two times anyway.

However, I like to see what the limits of the document oriented approach are and that you gave me those insights to think about - thank you for that.

Have a nice day and best Regards
Marcel
