### ISSUE TITLE
Mock the save method for a specific table

### ISSUE THREAD

**Issue by hypexr** [robconery/massive-js#288]
Hi,  I'm currently saving data like: 

```
var db = massive.connectSync(...)
db.login_sessions.save(...)
```

"login_sessions" is of course the table name.  Any ideas about how I should go about mocking this?

**Comment by robconery** [comment]
My first instinct would be "don't" - but that's just me :). I let my tests hit the DB. The other thing is that JS is pretty wide open RE mocks - it's pretty easy to create your own `db.login_sessions.save` function that returns what you want.

**Comment by hypexr** [comment]
I have some tests that hit a DB but for the most part I'm looking to test independently on my CI system.  I think my question is due to my lack of javascript experience.  How would I declare the mock save?  I've tried:

```
db.login_sessions = function() {
    function save(options, callback) {
        console.log("In login_sessions mock");
            return callback(null, {});
        }
});
```

where db is the result of the connection. With this approach it reports an error that login_sessions.save() is no longer a function.

If I do:

```
massive.login_sessions = function() {
    function save(options, callback) {
        console.log("In login_sessions mock");
            return callback(null, {});
        }
});
```

It doesn't properly overwrite the method and I tried:

```
db/massive.prototype.login_sessions = function() {
    function save(options, callback) {
        console.log("In login_sessions mock");
            return callback(null, {});
        }
});
```

and for both of those it reports can't set property 'login_sessions' of undefined.

Thanks for any help!!

**Comment by robconery** [comment]
The first try is close! The save function is private so you need to explicitly pop it on Db.login_sessions object (Db.login_sessions.save= function...)

**Comment by dmfay** [comment]
Entities are represented as objects. You're replacing the `login_sessions` object with a function which returns nothing, effectively wiping it out -- the `save()` defined in your outer anonymous function isn't attached to anything and disappears as soon as you exit the scope of the outer function. Try this:

```
db.login_sessions = {
    save: function () { /* your code */ },
    find: function () { /* etc */ }
};
```

**Comment by hypexr** [comment]
Works great!!  That makes sense and I'm glad to have a better understanding.
