### ISSUE TITLE
Type of id impacts findDoc behaviour

### ISSUE THREAD

**Issue by jagregory** [robconery/massive-js#298]
```
db.table.findDoc(1) -> { id: 1 }
db.table.findDoc('1') -> [{ id: 1 }]
```

I'm not sure what's actually happening in the second statement, but it seems like the parameter is just ignored entirely (`db.table.findDoc('abc')` yields the same result).

I would expect it to either magically work through type coercion, or not return any results because `'1' != 1`; however, it behaving like a regular find all query is not what I expected.

**Comment by robconery** [comment]
Yeah, this could be clearer :). If the parameter you send in (which in this case is `id`) corresponds to the primary key *and* the value is an integer (or a UUID), then result will be a single record. 

Otherwise it's treated as a simple where clause which returns multiple records.

**Comment by jagregory** [comment]
Closing this unless something is to be done.
