### ISSUE TITLE
Account for schemas in loadTables

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#30]
Right now we're just dropping things from `public` right on to the massive instance which works for many situations. I think it would be better to account for schemas as well - as that's [a good approach for keeping your DB uncluttered](http://www.postgresql.org/docs/9.4/static/ddl-schemas.html) when it gets to be rather large.

> There are several reasons why one might want to use schemas:
 - To allow many users to use one database without interfering with each other.
 - To organize database objects into logical groups to make them more manageable.
 - Third-party applications can be put into separate schemas so they do not collide with the names of other objects.

> Schemas are analogous to directories at the operating system level, except that schemas cannot be nested.

Our current tableSql pulls the schema (I think) so we have access to it. If the schema is `public` I say we do what we've been doing (pop it onto the massive instance). If it's not, namespace thus:

```javacript
db.my_schema.my_table.find()
```

**Comment by xivSolutions** [comment]
Was thinking this very thing as I was working on the query file walker...

**Comment by xivSolutions** [comment]
Do we want this to be bi-directional? In other words, do we want to be able to push schemas into the back end in some fashion when creating tables, by simply bolting the namespace on (somehow)? Or do we want to discourage willy-nilly schema creation by forcing folks to do this explicitly (even if it is a discrete/explicit massive api call).

**Comment by robconery** [comment]
Hmmm - good question. The only schemas we create are for document tables. Can you see if using “shema.doctable” works for `db.saveDoc`?

I’d like it if people could create their own schemas and we just respond - in the future we can do more :).



On March 8, 2015 at 4:54:59 PM, John Atten (notifications@github.com) wrote:

Do we want this to be bi-directional? In other words, do we want to be able to push schemas into the back end in some fashion when creating tables, by simply bolting the namespace on (somehow)? Or do we want to discourage willy-nilly schema creation by forcing folks to do this explicitly (even if it is a discrete/explicit massive api call).

**Comment by xivSolutions** [comment]
That's where I was wondering about for the moment. I kind of like the notion that if you want to add a schema, you need to be explicit instead of just bundling it on with a new table (doc or otherwise). People who know better will probably not do it that way, and people who don't know better will end up with a holy mess on their hands in the back end. 

I'll play with it though. We can make both something like you describe, and something like `db.AddSchema("schemaName")` and see how you feel about them.

**Comment by robconery** [comment]
Sorry - you lost me. For schemas I want people to work directly with the DB, I don’t think Massive needs to be involved. The only place we care about schemas is when we create document tables with `saveDoc` - other than that I want to namespace the tables if the schema exists (db.myschema.mytable.find()).

Make sense? So we shouldn’t need addSchema… unless I missed something?



On March 8, 2015 at 5:09:17 PM, John Atten (notifications@github.com) wrote:

That's where I was wondering about for the moment. I kind of like the notion that if you want to add a schema, you need to be explicit instead of just bundling it on with a new table (doc or otherwise). People who know better will probably not do it that way, and people who don't know better will end up with a holy mess on their hands in the back end.

I'll play with it though. We can make both something like you describe, and something like db.AddSchema("schemaName") and see how you feel about them.

**Comment by xivSolutions** [comment]
Nope. That was my original question, whether we wanted massive to be able to create schema's at all. Understood on the document tables thing.

**Comment by xivSolutions** [comment]
Pushed up the initial bits, which at this point only really load the tables in a schema onto a bolted-on namespace. Going to mess with execution next. This is not ready for merge yet. 

I'm thinking though. It's not critical now probably, but if we're loading schema, we may want to separate the schema load from the table load. Ultimately, it looks like we are expecting to load pg functions (is there a reason to load views, given our approach here??) and other potentially schema-bound items. 

We can always change things up when we run into this, but right now the schema load is intrinsic to the table load. We could duplicate that for whatever else we want, but...

On the other hand, I THINK loading this way ensures only schema to which the user has permissions are loaded.

**Comment by xivSolutions** [comment]
This works with the basic relational stuff. Needs to be played with. I brute-forced it for now, to see if the idea is something you want to pursue. Can be refined, I'm sure.  Gonna test/confirm for docs next.

**Comment by xivSolutions** [comment]
Works with docs for the basic load/save. Need to test doc queries. The code is atrocious in spots, but I got it working. I can pretty it up tomorrow after work, and test the hell out of it all. I'm sure I've missed more than one stupid thing here, but the concept works.

**Comment by xivSolutions** [comment]
Closed for now. Pushed to master. This stuff could use some exercising to make sure we haven;t missed something.
