### ISSUE TITLE
Bulk save documents within a transaction

### ISSUE THREAD

**Issue by Rub21** [robconery/massive-js#301]
Is there a way to load an array of objects  using  `saveDoc()` once?

For Example: 
```js
var arrayList =[{a:12},{b:45},{c:56},.... {xxx:45}];  
// Thousands if objects in the array. 

db.saveDoc("table", arrayList , function(err, res) {
   console.log('All rows were saved ! ');
});
```

each objects should be a row!

**Comment by robconery** [comment]
Hmm - no not at the moment but it would be a damn nice feature to have. You can do this fairly easily (I think) if you sniff out an array in `saveDoc`. You would have to loop over it with a transaction, adding the documents in a bulk insert. @xivSolutions is pretty good at this stuff... maybe he'll weigh in.

Any chance you'd want to give it a try?

**Comment by dmfay** [comment]
Not sure you'd need an explicit transaction since you can pass multiple items in the `VALUES` list -- but concatenating thousands of strings might drag. That sounds like it'd be a problem either way though, maybe something with `COPY` from stdin? ref https://github.com/brianc/node-postgres/pull/232

**Comment by xivSolutions** [comment]
It can be done using the multiple insert statement as Dian describes, but you have to keep track of how many rows and how many params you are using per command. There are limits, usually imposed by the driver. Also, the COPY would work, although that way ignores malformed or invalid inputs, and your insert can become a mess if your SQL gets assembled wrong.

I've been thinking on proposing/adding some bulk insert stuff, maybe as a V3 thing.

@robconery I think it's time, if we can ever make the time. V3 all the things.

**Comment by dmfay** [comment]
I'm interested in helping out on v3 too, and I do have some time to work on Massive. Do you guys have a roadmap anywhere or is it all ideas and the (abortive?) bluebird branch at the moment?

**Comment by xivSolutions** [comment]
We've been spitballing a little. Yeah, I personally feel that Node/v8 has sufficient support for ES6 + in-build promises that there is no need to clutter things up with a third-party Promise lib. So, yeah, I think the 'bluebird' branch is more of an experiment, and an abortive one. 

We've discussed going full-tilt with ES6, and also trying to slim things down a bit. The current code base is getting a little scattered (I think, anyway). 

I can;t speak for Rob, but to me, the only thing preventing a start here is available time (which has been scarce for me of late) and some roadmapping/api discussions/decisions.

**Comment by dmfay** [comment]
How/where do you all want to have those discussions? There're a couple of items I have in mind but I don't know if github issue threads really lend themselves to mapping a variety of topics out like that.

We've been using ES6 promises for a while now (with a custom wrapper to promisify Massive methods on demand) and it's been working pretty well so I definitely agree there's not much call for a thirdparty library there.

**Comment by robconery** [comment]
I guess we just spin up some milestones and start lobbing issues in that we can work towards. I can also open a v3 branch that we can work against.

And yeah - if we go the ES6 route entirely, our codebase will decrease "massively". LOL.

**Comment by robconery** [comment]
I just need to finish this book (this week, I think) and then I'm all over this.

**Comment by cjnqt** [comment]
Great to hear you're moving to ES6!

**Comment by gaastonsr** [comment]
Promises + Transactions please <3

**Comment by robconery** [comment]
Happy to do promises - I'll have to see if a transaction abstraction makes any sense. I'm closing the for now.
