### ISSUE TITLE
Reconnect to DB

### ISSUE THREAD

**Issue by Rub21** [robconery/massive-js#302]
Whats would be the best way to reconnected to db to reload all tables , I've created a table using `hapi-node-postgres` . I saw previous tickets where say that massive.js load all tables when it is starting up  and need to reconnected to DB to load the new tables. 

```js
var db= massive.connectSync({
    connectionString: config.connectionString
  });
.
.
.
client.query('CREATE TABLE ' + idstr + '( id serial PRIMARY KEY,  idsrt varchar(50),  time integer,  body jsonb );', function(err, result) {
  db=massive.connectSync({
    connectionString: config.connectionString
  });
  });
```

do we need close the previous connection or only set up again the connection?

**Comment by robconery** [comment]
I suppose calling `db.loadTables` would do the trick. Have you tried that?

**Comment by Rub21** [comment]
Thank you  @robconery , it works fine! :)
