### ISSUE TITLE
Trigger is not firing for the Insert from the application

### ISSUE THREAD

**Issue by nannastudy** [robconery/massive-js#313]
I am really satisfied using the Massive.js in my application. Recently I encountered an issue which I am not able to resolve.

Problem background : 
I have a function in the DB as follows
	CREATE FUNCTION question_tsv_trigger() RETURNS trigger AS
	$BODY$
	begin
	  New.weighted_tsv := to_tsvector('swedish',coalesce(New.body->>'qtext','')::text);
	  RAISE NOTICE 'TRIGER called on %', TG_TABLE_NAME;
	  return New;
	end
	$BODY$
	LANGUAGE plpgsql VOLATILE
	COST 100;

Trigger in the DB:
	CREATE TRIGGER insert_upd_question_tsvector BEFORE INSERT OR UPDATE
	ON myschema.cf_question
	FOR EACH ROW EXECUTE PROCEDURE question_tsv_trigger();

 I am inserting a record from my application using following code :
            db.myschema.cf_question.insert({
               cf_question_type_id:request.payload.type_id,
               cf_question_category_id:request.payload.cat_id,
               lang:request.payload.lang,
               body:request.payload.body
            }
The above app code inserts the record in the DB, but the respective trigger in the database is not triggered hence the "weighted_tsv" columns is empty for this record.

But if I insert another record from the postgre's psql, it will insert and the respective trigger is working.

What could be the problem ? Why trigger is not working if I  insert from the application ? Am I doing anything wrong ?
Any help would be really really appreciated.

Thanks
Kiran

**Comment by dmfay** [comment]
When you're connecting and inserting a row with the trigger firing successfully, is it as the same user you're connecting Massive with? Nothing looks wrong to me in what you've posted (and I'm using `BEFORE UPDATE` triggers with Massive myself) so the first thing I'd check is permissions & ownership.

**Comment by nannastudy** [comment]
HI Dian Fay,

Thanks for the response. Yes, it is the same user I am connecting with Massive.
The table is in a different schema, but while inserting I mentioned full namespace "schema.table".
Can you please elaborate on permissions and ownership ?

regards
Kiran

**Comment by nannastudy** [comment]
After enabling logging in the database, I figured the problem in the insert.
The JSON that was inserted had the "qtext" mispelled and the coalesce was returning '' and hence the tsvector was not having anything in the column. 
I was able to fix the issue, after correcting the JSON input . 

Thanks
Kiran
