### ISSUE TITLE
document partial updates

### ISSUE THREAD

**Issue by bguiz** [robconery/massive-js#315]
postgres 9.5 actually does allow partial document updates for JSONB fields: https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5#JSONB-modifying_operators_and_functions

"In 9.3 (and to a greater extent in 9.4), JSONB data could be extracted using various functions and operators, but nothing that could actually modify the data. As of 9.5, JSONB data can now be modified."

In the massive-js docs: From: http://massive-js.readthedocs.io/en/latest/document_queries/

"You can update as well - but PostgreSQL does not support partial updates, so if you do an update it's a full swap. We're considering supporting partial updates at the code level (basically running a diff) - but this can be quite difficult to get right. For now, it's a full replace:"

... so question: Does massive-js now support partial JSONB updates too, when run against a postgres 9.5 database? If not, can we add support for this?

**Comment by dmfay** [comment]
The documentation is out of date -- there's a `setAttribute (id, key, val, next)` function which uses `jsonb_set` to update.

**Comment by bguiz** [comment]
@dmfay The documentations is ... a little sparse on setAttribute too: http://massive-js.readthedocs.io/en/latest/API/json_documents/

(it only has the function signature, and nothing else)

**Comment by dmfay** [comment]
I added some more information to http://massive-js.readthedocs.io/en/latest/document_queries/ but feel free to update the API docs too!

**Comment by bguiz** [comment]
Additionally, I'd like to be able to do a document update with a query (not just the ID), for example

```js
db.doggies.setAttribute({
  sex: 'male'
}, 'name', 'rover', (err, result) => { /* ... */ });
```

(note that this implies being able to update multiple documents with one query)

Further to this, I'd like to be able to set multiple attributes at the same time

```js
db.doggies.setAttribute({
  name: 'rover',
}, {
  sex: 'female',
  kennel: 123,
}, (err, result) => { /* ... */ });
```

From what I understand about [`jsonb_set`](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#jsonb_set_function), this may require multiple statements, and therefore a multi-statement transaction of some sort.

**Comment by bguiz** [comment]
@dmfay should I open a new ticket for the above since you've closed this one?

**Comment by dmfay** [comment]
yes, please do. In the mean time you could use a script or function, if you don't need to be flexible with what you're setting.
