### ISSUE TITLE
Combining findDoc()  or where() with saveDoc()

### ISSUE THREAD

**Issue by bguiz** [robconery/massive-js#319]
... essentially an upsert on a document where the `id` primary key is unknown. How do we do this with massive-js?

Currently it looks like we can do `findDoc()` or `where()` with one statement, get the `id` if one was found, then `saveDoc()` to update or insert. That's two separate statements. Would it be possible to accomplish the same with just one statement?

**Comment by dmfay** [comment]
The short answer is 'no'. If you supply criteria without the primary key there's no guarantee they match at most one row (barring a unique constraint, but that's its own special case). It's why the existing upsert functionality for regular tables in Massive is predicated on the presence or absence of the primary key in the criteria, and why Postgres' native `ON CONFLICT` clause has similar restrictions.

This principle can be worked around in specific situations, but there's no general solution -- or rather, the general solution is "know your primary key, if it exists". If the document you may have created was inserted through Massive, the document returned in the callback will have the primary key.
