### ISSUE TITLE
Comprehensive Docs

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#32]
We have Jekyll right here in Github with Github docs, but I think there's probably a better solution - AND I don't like the docs living as a branch in the project itself.

There are [solutions like MkDocs](http://www.mkdocs.org/) which seems pretty neat, and there's also some homespun stuff we could do (see gh-pages theme currently). I like the idea of razor-simple, all in one page references (like Backbone).

I don't think our stuff is so complicated as to need a huge site, but I *do* like lots of examples and a quick start.

**Comment by xivSolutions** [comment]
I think you cover the essentials pretty well in the read me. However, I agree that some examples and a "how to use this if you're brand-new" might be good. Basic and well documented example project?

I really like your style with the narrative bits like the read me. We should probably stick to that there, but I am happy to take on a more terse and simple set of examples and/or reference if you decide where the best place for it to live should be.

**Comment by robconery** [comment]
I just want a lot of code that’s organized and easy to find/read. I was just looking for something simple - MkDocs looks easy; surprised Jekyll doesn’t have something like it.

The one really nice thing about using gh-pages is flexing Github for community/doc support (as if). 


On March 8, 2015 at 4:51:02 PM, John Atten (notifications@github.com) wrote:

I think you cover the essentials pretty well in the read me. However, I agree that some examples and a "how to use this if you're brand-new" might be good. Basic and well documented example project?

I really like your style with the narrative bits like the read me. We should probably stick to that there, but I am happy to take on a more terse and simple set of examples and/or reference if you decide where the best place for it to live should be.

**Comment by xivSolutions** [comment]
If we used MkDocs or something like it, do you wanna host in gh project pages (with the attendant orphan branch in repo), separate repo of it's own (maybe on the massivejs org site you set up? Or a new repo Massive Docs?) or somewhere else?

I'm happy to jump in and start messing with it, but the hosting decision is really in your court. On quick read, looks like we could use MkDocs, drop it in gh project pages, and easily move elsewhere if need be later?

**Comment by robconery** [comment]
Yeah we can host in gh-pages. I keep feeling like we should be able to flex Jekyll somehow; tell ya what lemme take a stab at it over the next week or so. I have a template I really like - maybe I can get it to work with Jekyll (which I know pretty well).


On March 10, 2015 at 3:11:38 AM, John Atten (notifications@github.com) wrote:

If we used MkDocs or something like it, do you wanna host in gh project pages (with the attendant orphan branch in repo), separate repo of it's own (maybe on the massivejs org site you set up? Or a new repo Massive Docs?) or somewhere else?

I'm happy to jump in and start messing with it, but the hosting decision is really in your court. On quick read, looks like we could use MkDocs, drop it in gh project pages, and easily move elsewhere if need be later?
