### ISSUE TITLE
Possible reasons why a table is not attached to massive?

### ISSUE THREAD

**Issue by jlippold** [robconery/massive-js#323]
Any reason why this would work
```
	db.run("select * from crap", function(err, res) {
		return callback(null, res);
	});
```

but this returns `Cannot read property 'crap' of undefined`
```
	db.public.crap.insert(userObject, function(err, res) {
		console.log(err);
		return callback(null, res);
	});
```

It's as if massive is skipping this `crap` table. The table was created like
```sql
	CREATE TABLE IF NOT EXISTS public.crap (
		crap_id SERIAL,
		firstName text NOT NULL,
		lastName text NOT NULL,
		email text UNIQUE NOT NULL
	);
```

I'm sure it's something stupid on my end but I'm pulling my hair out

**Comment by jlippold** [comment]
I tried logging what tables are connected to massive

```
	var tables = db.tables.map(function(table) {
		return table.name;
	});
	console.log(tables);
```
and I get

```
web_1  | [nodemon] restarting due to changes...
web_1  | [nodemon] starting `node ./bin/www`
web_1  | DB connected
web_1  | Express server listening on port: 3000
[nodemon] clean exit - waiting for changes before restart
web_1  | [ 'districts',
web_1  |   'migrations',
web_1  |   'roles',
web_1  |   'schools',
web_1  |   'session',
web_1  |   'user_roles',
web_1  |   'users' ]
web_1  | Cannot read property 'crap' of undefined
web_1  | GET /crap 500 22.723 ms - 1143
```

Why isn't crap in the table list, it's so odd. I can select & insert fine using pgAdmin

**Comment by xivSolutions** [comment]
Can you check to see what happens of you remove the `public` like so:

```js
    db.crap.insert(userObject, function(err, res) {
        console.log(err);
        return callback(null, res);
    });
```
When Massive loads the tables, items in the `public` schema are bolted directly onto the Massive instance itself, without the `public` qualifier. I suspect that is the issue, but if not, let us know.

**Comment by dmfay** [comment]
`crap` also needs to have a primary key and be visible to the user you're connecting with.

**Comment by jlippold** [comment]
@xivSolutions and @dmfay , thank you

The combined solution of removing `public` AND adding a primary key made the table show up.

```
	CREATE TABLE IF NOT EXISTS public.crap (
		crap_id SERIAL,
		firstName text NOT NULL,
		lastName text NOT NULL,
		email text UNIQUE NOT NULL,
		PRIMARY KEY(crap_id)
	);
```

This should probably be added to the documentation somewhere.. but basically if tables aren't detected by massive, devs need make sure the table has a primary key

**Comment by xivSolutions** [comment]
But...who would define a database table without a primary key? :trollface: 

Kidding :-) Glad you got it resolved!

**Comment by jlippold** [comment]
yea I actually made a crap table just to test it and figured, ohh im testing who needs a key anyhow. Big mistake 💩
