### ISSUE TITLE
PubSub support

### ISSUE THREAD

**Issue by deoxen0n2** [robconery/massive-js#325]
As I currently understand, this feature is discussed in #176 and might be get implemented in the future.

But in the mean time, is there a support for `events` (like in `pg` module: https://github.com/brianc/node-postgres/wiki/Client) or does Massive expose the client (`pg` client)? Sorry I couldn't find in the docs.

Best Regards :)

**Comment by jmealo** [comment]
@deoxen0n2: check out: https://github.com/posix4e/jsoncdc and: https://github.com/JarvusInnovations/

What is your use case? Is it full-blown publish/subscribe that you are looking for? (or would you just like to attach event handlers to tables and stream changes sequentially?)

Do you need at least once delivery? How about in order? There are a lot of options depending on your requirements.

**Comment by robconery** [comment]
I might recommend you look into EventEmitter and pub/sub your own events maybe? We used to have events in there but they didn't make much sense.

**Comment by deoxen0n2** [comment]
My use case is streaming changes to clients via WebSocket (say, incoming new order or existing order is updated). So my plan is to use `NOTIFY` query on Postgres side when the new row is inserted or the existing row is updated and then streaming those changes via WebSocket.

I'm very new on PostgreSQL so apologize in advance if I missed something.

**Comment by robconery** [comment]
No apologies needed :). You can do LISTEN/NOTIFY with an EventEmitter but... that's a long way round. Are you thinking of using socket.io or something?

Another idea: you could use Firebase and keep things ultra simple :).

Anyway: yeah you might need to use node-pg directly for this.

**Comment by deoxen0n2** [comment]
OK then, I think I would go with `node-pg` directly for this functionality. Thanks you both of you and nice module by the way :)
