### ISSUE TITLE
GRANT on MATERIALIZED VIEW not setting ACL properly

### ISSUE THREAD

**Issue by AlphaDork** [robconery/massive-js#326]
Version: Massive v.2.5.0, Postgresql v9.4.x, v9.5.x

Problem: Executing the following SQL via Massive (v.2.5.0) results in a properly constructed view, BUT a blank ACL.

Symptom:  When I execute a query on this view with the "MyReadOnly" role, I get a access violation: "permission denied for relation catalogview"

Additional: Executing the SQL via PSQL or a PGIII window works as expected. Queries run under "MyReadOnly" role succeed. ACL is populated as expected: "MyReadOnly=r/",

Also note that "MyReadOnly" role has been granted USAGE on the schema.

```SQL 
CREATE MATERIALIZED VIEW myschema.catalogview AS
     SELECT cid, body, search, search_category, search_keyword
     FROM myschema.mytable;

CREATE INDEX index_search ON myschema.catalogview USING gin(search);

ALTER TABLE myschema.catalogview OWNER TO "MySuperUser";
GRANT SELECT ON catalogview TO "MyReadOnly";
```

**Comment by robconery** [comment]
The JS code would be helpful here as well :) - thanks for a nice issue too!

**Comment by robconery** [comment]
Oh - also I should add that your view needs to be readable from the INFORMATION_SCHEMA query we do here: https://github.com/robconery/massive-js/blob/master/lib/scripts/views.sql

This means that whatever account you use to instance Massive needs to be able to read from this query.

**Comment by AlphaDork** [comment]
You are familiar with the Javascript - you wrote it LOL. It's taken from your pg-auth repo. So maybe I should have filed over there come to think of it. 

In builder.js - 
```javascript
exports.install = function(){
  var db = Massive.connectSync(dbConfig);
  var sqlFile = decideSqlFile();
  var sql = fs.readFileSync(sqlFile,{encoding : "utf-8"});
  return db.runSync(sql);

```

**Comment by AlphaDork** [comment]
Confirmed that I'm a bozo. LOL. Can I blame it on the new puppy and lack of sleep?  Calling a function later in my SQL load that blew away the view and rebuilt it without granting access to the read.  

Thank you for your patience! IOU - 1 largish beer.

**Comment by robconery** [comment]
LOL no problem! Glad its solved :).
