### ISSUE TITLE
Massive failing when trying to use on Electron app

### ISSUE THREAD

**Issue by navtek** [robconery/massive-js#328]
Hi,

I'm having the next issue when trying to include 'massive' inside an electron app, it seems it has something to do with some other modules that massive depends on. 

I made my tests trying the node-postgres module and I can get my application running with no problem.

I tried rebuilding some modules but still getting the same error. 

This is the error:

App threw an error during load
Error: Could not locate the bindings file. Tried:
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/build/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/build/Debug/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/build/Release/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/out/Debug/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/Debug/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/out/Release/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/Release/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/build/default/deasync.node
 → /Users/mb/Documents/electron-quick-start/node_modules/deasync/compiled/6.5.0/darwin/x64/deasync.node
    at bindings (/Users/mb/Documents/electron-quick-start/node_modules/bindings/bindings.js:88:9)
    at /Users/mb/Documents/electron-quick-start/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/Users/mb/Documents/electron-quick-start/node_modules/deasync/index.js:76:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

I'm on Mac OS X El Capitan 10.11.6, npm 3.10.8 and node 6.9.1

**Comment by robconery** [comment]
Oh dear - yeah that won't work. First: we're getting rid of deasync in v3, which we're still planning. 

The problem is that deasync needs native bindings, which means every client that uses your Node app will need to have the ability to compile these native bindings. That won't work.

If you need data storage on the client I'd highly recommend NeDB, which is a document store that works like SQLite. If you need to reach out over the network to connect to PostgreSQL, Massive isn't going to work for you.
