### ISSUE TITLE
Syntax for updating multiple rows with different data

### ISSUE THREAD

**Issue by Aedaeum** [robconery/massive-js#334]
Example raw posgres query:
```
update users as u set -- postgres FTW
  email = u2.email,
  first_name = u2.first_name,
  last_name = u2.last_name
from (values
  (1, 'hollis@weimann.biz', 'Hollis', 'O\'Connell'),
  (2, 'robert@duncan.info', 'Robert', 'Duncan')
) as u2(id, email, first_name, last_name)
where u2.id = u.id;
```

Is there a way to do this using massivejs syntax without having to write the raw sql query like above?

**Comment by xivSolutions** [comment]
There's no way to do this in Massive directly - any way we would implement this would require iterating a collection of records to update, and while I can't speak for @robconery or @dmfay the complexity involved would outweigh any percieved gain, when it is just as simple (simpler, actually, IMHO), for the client code to perform the iteration like so:

 ```js

// some collection of users needing to be updated, however you arrived here:
var usersToUpdate =[
  {1, 'hollis@weimann.biz', 'Hollis', 'O\'Connell'},
  {2, 'robert@duncan.info', 'Robert', 'Duncan'}
];

usersToUpdate.forEach(function(user) { // ES6/2015 array.prototype syntax
  //include the PK in the criteria for an update
  db.users.save({id : 1, email : "test@example.com"}, function(err, updated){
    //the updated record for the new user
  });
});

```

Massive does allow updating of multiple records which meet a common criteria with the *same values* like so (example from the `table_spec.js` test file):
```js
    it('updates multiple products', function (done) {
      db.products.update({in_stock: true}, {in_stock: false}, function(err, res) {
        assert.ifError(err);
        assert.equal(res.length, 2);
        assert.equal(res[0].id, 1);
        assert.equal(res[0].in_stock, false);
        assert.equal(res[1].id, 2);
        assert.equal(res[1].in_stock, false);
        done();
      });
    });
```

Also, Massive *does* allow for insertion of multiple new records (a far, far more common scenario then updating multiple existing records with different data in each field set) like so (again, from `table_spec.js`):

```js
    it('inserts multiple products', function (done) {
      // you could also call save() here with the same result):
      db.products.insert([{name: "A Product"}, {name: "Another Product"}], function (err, res) {
        assert.ifError(err);
        assert.equal(res.length, 2);
        assert.equal(res[0].name, "A Product");
        assert.equal(res[1].name, "Another Product");
        done();
      });
    });
```

Unless I have missed the point of what you are trying to do in your example completely, I would recommend walking the collection client side. If it is a one-off, and/or a particularly large number of records, then yes, you will likely be better off writing some raw sql. 

Can you elaborate more on the problem you are trying to solve?

**Comment by Aedaeum** [comment]
@xivSolutions Thanks for the quick reply

I have a chat application that stores stats for chat messages, such as how many messages per user. In order to load balance, a certain number of these messages are stored in a log file on the file system and then at a specific time, they are aggregated into the database.  I wanted to prevent a database write for every message sent in the system.

Since the log file will contain messages from all users, when the parsing algorithm completes, it will return stats that need to be updated for those users and each user has their own stat table, hence I need to update multiple tables.

Your solution was to iterate over all the data one by one. I'm curious as to what kind of strain that might put on the database, which is why I was looking for an all-in-one update solution. I am very interested in your incite as to maybe a better method to do this or insight into my current method of load balancing. I don't really know best practices when it comes to writing to a database.

**Comment by xivSolutions** [comment]
@Aedaeum - Yes, that does sound like a special case, where iterating is not necessarily the best way to go. And, let's be clear, I did not say iterating one by one was the solution to your problem, just that any solution we would need to implement behind the scenes would also need to iterate the items to be inserted as well. 

It sounds like you have a large number of records that need to be updated. No matter how you slice it, there is a lot of database writing that needs to be done here, but possibly there is a better way to manage it. I'll have to think on this, and possibly @robconery might have some insight as well. 

I can say that this is an edge case which Massive does not try to address directly.

**Comment by Aedaeum** [comment]
@xivSolutions - In the meantime I was looking at other database solutions (ORMs) that might support the kind of query I mentioned. I'm currently taking a look at [Waterline](https://github.com/balderdashy/waterline) but obviously, I would prefer for all the work I've done with Massive not to go to waste. I will make sure to get yours and robconery's thoughts before I make any big decisions.

**Comment by dmfay** [comment]
Couple questions:

* Why are you generating one stats _table_ per user? If the idea is that it's got a "key" and a "value" column so you can change which statistics you're collecting on the fly without a schema update, consider using a JSON field in your users table instead. If you're aggregating historical data, look into a materialized view on a single stats table with a version column. It also bears thinking about how you'd calculate systemwide stats (eg total unread messages, or something): it's very difficult with your data spread across an arbitrary number of tables, very easy if it's all in one place. There may be reasons to have one table for each row in another table, but it's worth looking into alternatives when possible.

* Are you actually looking at a level of throughput that requires deferring writes? Postgres isn't designed for superhigh write volume on the order of something like Cassandra, but it can keep up with quite a bit. If realtime writes to the database are in fact a bottleneck... things get weird. `COPY FROM` file/stdin into a temporary table, then `UPDATE FROM` into your actual table? You'd have to have a single statistics table (or a single field on your users table) to get away with that though; even if you got something working with your multi-table schema, you'd still have to iterate the incoming data to figure out which ones to update, so you wouldn't be saving anything.

**Comment by Aedaeum** [comment]
@dmfay I should clarify that it's one stats table where the id of the rows is a foreign key to a user in the users table. I didn't mean to create the confusion that there are multiple tables being created. That being said, I do like the idea of not even having the stats table to begin with and just using a JSON object as one of the user fields for each users stats.

The issue still remains: how do I update multiple rows at the same time, of different users, without a massive amount of iterative writes to the database?

**Comment by dmfay** [comment]
In short: you don't. Even the raw query you posted is iterating over the temporary object created by `VALUES`; it's just performing the iteration as close as possible to the data to minimize roundtrip time. This can't be abstracted out without either increasing write time or doing redundant work to batch the data. The work _must_ happen in the database engine in order to realize best performance.

Using `COPY FROM` to stream your logfile into temporary storage and updating your actual table from there like I suggested would keep the iteration in the db engine and leverage your PK/FK indexing. You should be able to do that with a script or database function, since Massive lets you invoke those directly. But as John said, any solution that involves using a data mapper or an O/R mapper to build and emit an `UPDATE` statement or statements will be suboptimal: mappers are a 99% solution, and this is a 1% problem.

**Comment by Aedaeum** [comment]
@dmfay - I can't imagine I'm the first person to need to update multiple users at the same time with different data. That being said, can you suggest a better way? Also can you point me to how to use this `COPY FROM` to put the log file in temporary storage, I've never seen that before.

Lastly, would it be better just to invoke the update on every message? I would give an example like twitch chat, where people are constantly chatting and all those messages need to be updating a count for each user.

**Comment by dmfay** [comment]
You're absolutely not the first person to run up against something like this, but that doesn't change the fact that mappers simply aren't the tool for this particular job :) For `COPY`, look at the (extensive!) Postgres documentation for whichever version you're using.

Not knowing the particulars of your situation, I would update on message unless load testing at the scale you're planning for shows noticeable performance degradation compared to not updating on message; there's little point in solving problems you don't have. But I'd also think about where and when the stats you're collecting are used, and just how current they need to be, given you were already willing to sacrifice realtime calculation for throughput. Could you get away with simply refreshing a materialized view from an independent daemon or scheduled task? If they're only visible on request, are they simple enough to calculate on the fly without storing anything at all?

**Comment by Aedaeum** [comment]
My ignorance is showing here... What is a "materialized" view?

In order to know that a user has sent X amount of messages, something needs to be stored. If I was storing a total message history, then yes I could use the "on demand" approach to filter out a single user, but I'm not storing history.

Currently, every time a user sends a message, it gets added to a log file on the file system. That log file is then later parsed and entered into the database to store the "new" stats about a users messages. That file is then cleared for the next batch of messages which are cached in memory at a specified interval. All of this was to reduce load on the database and reduce load on the file system. We're talking an update rate at about every 5 minutes.

You make a very good point about trying to solve a problem that I don't have right now. I do not have anywhere near the traffic necessary to know how many `req/s` it would take to drop performance of the site with a database write per message. My goal is to future proof.

Any more insights you have, I would be much obliged to hear as I am a total database newb.

**Comment by dmfay** [comment]
A materialized view is a view (in other words, a prewritten `SELECT` query) whose results are physically stored and must be manually refreshed. So it's not realtime, but it's faster to query than a comparable standard-issue view. Won't help you if you're not storing message history, though.

It's honestly sounding like you should look into Redis or something along those lines as a transient store for messages (especially with the ability to set a time-to-live on insert), and update stats in Postgres as necessary from messaging event handlers and so on. If you know the primary key, updates are dirt cheap. I wouldn't worry about that until you're in real danger of becoming the next Twitch.

Future-proofing is great but it's necessarily an unattainable goal. What you should be trying to design is something that meets your current needs as simply as possible, scales up to a reasonable degree, and is then easy to expand or replace once it reaches its limit. What you've got sounds like a complex system with a lot of moving parts, intended to handle far more than you're going to be throwing at it for the foreseeable future -- overengineered rather than future-proofed. Build something simple and sufficient; if it does exceed your designed capacity and you need to go back to it, that's the best possible problem to have.

**Comment by Aedaeum** [comment]
@dmfay - You are really make my day today, excellent information, thank you so much.

Coincidentally I am already using Redis for session storage. I didn't even think about using it for caching message logs. How would caching the messages in Redis transfer over to saving the stats per user in Postgres? I am indeed using primary keys to insert the stats.

You're absolutely correct about over-engineering. I think I've given this almost a little too much thought for my use case at the moment haha. I tend to do that quite often, which translates into very complex functions which, in the end, could have been reduced to a few lines of code had I realized the simplicity in the first place.

**Comment by dmfay** [comment]
Nothing complicated: when someone enters a message, the body goes to Redis and you update their row in the users table in Postgres. A script or function would be best for this since that way you don't have to retrieve the original count first just to increment it.

**Comment by Aedaeum** [comment]
I see, so Redis would essentially contain a dynamic stat table and when a user sends a message, I would push the change to Redis (increment the amount) and then the result would be written to the Postgres stat table?

**Comment by dmfay** [comment]
No -- Redis would contain your messages, replacing your logfile (transient data). Postgres has your users and statistics (permanent data). Adding a new message becomes a two-part process where, instead of appending to the log, you insert the new message into Redis and update the statistics in Postgres.

**Comment by Aedaeum** [comment]
You said I would be able to skip the query for the original count by using Redis, which to me means that when a message is saved to Redis, it wouldn't be the raw message (like it is now) but just the stats of that message being saved.

That being said, it also means I would have to load the stats from Postgres for all online users into Redis to make sure the count stays accurate, if I want to skip that step. I guess I'm just not sure how you're proposing I can skip the step of querying for the "current" count of messages from a user, in order to add the new count.

**Comment by dmfay** [comment]
The point of using a function or script to update the sent count is that when a message is sent, all you have is the user id. You _could_ issue a `SELECT` query to retrieve the statistics, add 1 to `sent`, and issue an `UPDATE` to persist it; or, you could invoke a function which emits `UPDATE statistics SET sent = sent + 1 WHERE user_id = $1` and thus increment the count with one roundtrip to Postgres instead of two.

The statistics stay in Postgres; Redis in this scenario only exists to store messages.

**Comment by Aedaeum** [comment]
Ohhhh, you meant a SQL script, there's where I got confused.

How would I do that with Massive? I've been trying to figure out how to execute raw SQL code through massive and I can't find it in the docs.

**Comment by dmfay** [comment]
It's here: http://massive-js.readthedocs.io/en/latest/functions/

**Comment by Aedaeum** [comment]
Thanks for that link, I guess I'm blind haha.

I was able to create a function that updates the count with a single query after a bit of fiddling. The only caveat that I see now is the purpose of the cache. It existed originally to reduce database activity, but if I'm adding the messages to Postgres right after they're sent, I really don't see the purpose of the cache anymore, unless you're implying that I would continue with my previous implementation of waiting a matter of time and then iterating over all the logs, then saving them into Postgres. You eluded to this when you mentioned the "time-to-live on insert" with Redis.

I hope I'm not taking too much of your time, but your advise is invaluable to me at the moment; I really appreciate it.

**Comment by dmfay** [comment]
Caching is a problem you can address later, this is about storage. Put your messages in Postgres if you want to keep them permanently (you could clean them up on a schedule or something, but that's extra work); put them in Redis with a TTL if you want them to expire automatically. The latter scenario seems more like what you want. And either way you'll update the stats in Postgres as you add a message.

You shouldn't use the log file as storage at all -- the reason we have databases in the first place is that flat files aren't very good at it!

**Comment by vitaly-t** [comment]
>  I'm curious as to what kind of strain that might put on the database

A bad one, as the database IO is the most expensive resource in a scalable system.

>It sounds like you have a large number of records that need to be updated. No matter how you slice it, there is a lot of database writing that needs to be done here

Not true, a single multi-row update requires just query to update everything at once, and it is atomic in nature, meaning: if one update fails, none will succeed, so no transaction required.

Multi-row update is the only right approach for the described sitiation.

**Comment by dmfay** [comment]
Multi-row updates can't apply different data to each row.

**Comment by vitaly-t** [comment]
> Multi-row updates can't apply different data to each row.

They can, and they do. See the very example this question started with, it shows you how it works. Applying different data to each row is exactly what it does.

**Comment by dmfay** [comment]
You can effectively join a table in SQL and update by key, sure, but this was about going through the table API in Massive, which doesn't do that. The original problem was settled by reframing the question in a way that obviated the necessity of the multi-row update entirely, so I don't really see what's to be gained by dropping in a month later to quibble over minutiae.

**Comment by robconery** [comment]
Hi @vitaly-t - thanks for dropping in. Love your pg-promise project, I think we might use it in vNext of Massive :). Given that, how would you do this with pg-promise? I guess with the SQL example you mention?

**Comment by vitaly-t** [comment]
I wasn't going to mention pg-promise here, not to upset anyone, but since the author asked... :)

The library does it in a very generic way, it can generate in the same way:

* single-row insert
* multi-row insert
* single-row update
* multi-row update

Here're some examples:

* [Multi-row insert with pg-promise](http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise/37302557#37302557)
* [PostgreSQL multi-row updates in Node.js](http://stackoverflow.com/questions/39119922/postgresql-multi-row-updates-in-node-js/39130689#39130689).

Bascially, it is all done through generic type [ColumnSet](http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html) that's highly reusable, and optimized for performance - it is smart enough to cache query generation, so every repeated query is generated much faster, with the absolute minimum of the query formatting that's required.

**Comment by robconery** [comment]
No problem at all :) we're all friends here. As long as it's constructive...

**Comment by vitaly-t** [comment]
@robconery cool :) if you have any questions - let me know ;)

**Comment by Aedaeum** [comment]
@vitaly-t Hmm... Well this changes my approach yet again. I'm very glad you commented on this issue :)

**Comment by Aedaeum** [comment]
@robconery Do you think this is functionality that might come to Massivejs in the future, seeing as pg-promise compensates for this so-called "edge case"?

**Comment by robconery** [comment]
We're working on vNext right now so... yes I think so. At least I queued it up for @xivSolutions to take a swing at :).

**Comment by dmfay** [comment]
That all said (& it is a cool feature!) @Aedaeum I would still caution against using it as you originally intended to -- the deferred-write architecture you came up with is much more complicated than you have a demonstrated need for, and that's all too frequently the kiss of death for software projects.

**Comment by Aedaeum** [comment]
@dmfay I agree, I don't have the throughput necessary to bottleneck the database with updates on every message. That being said, when I do, Massivejs will have the facilities to accommodate my need.

**Comment by robconery** [comment]
I should probably not get into this, but ... it's worth it...

If you're updating in a loop, constantly, forever - that *will not* "bottleneck" your database. Connection pooling (which we use) mitigates the opening/closing cost and the MVCC will prevent locking, assuming you aren't trying to write twice.

What will "bottleneck" your database is bad indexing and non-sargeable queries that use full table scans. *Writes are cheap*, especially single-record writes. If you write in blocks, unbound, you run the possibility of hanging an MVCC transaction over multiple records. *That* could be bad for your system depending on your need for "clean" data.

**Comment by Aedaeum** [comment]
What do you mean by "write twice" the same data? Or do you mean writing something like: 
```
user.update('foo'); 
user.update('bar');
```
rather than just updating once per tick, so-to-speak?

**Comment by vitaly-t** [comment]
> If you're updating in a loop, constantly, forever - that will not "bottleneck" your database.

This is what I argue against (not to start a flame here 😄) in [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost).

**Comment by robconery** [comment]
@Aedaeum by "write twice" I mean updating the same record in separate transactions. This will cause a lock and keep the connection open, removing it from the pool, which is bad. It still won't slow your application down.

**Comment by robconery** [comment]
@vitaly-t  To expand on what I mean RE scaling: small updates via primary key are incredibly cheap. Inserts too as long as the indexing is happening in the background. You can pound on PostgreSQL pretty heavily before anything bad happens, and even then Node, with it's single thread, would have to do *a lot* to put a dent in it.

If you're running multiple instances of Node then yes, you could firehose PostgreSQL pretty good and possibly chew up all 100 connections. But I would put money down that it's not going to be due to individual operations - it would be due to updating 100 rows and causing locks, which soak up a connection. In that case you want quick in, quick out.

**Comment by Aedaeum** [comment]
@robconery Define a "separate transaction". The code I posted would update the same user twice with two different calls. That, to me, means different transaction. But if you mean two parts of the application trying to update the same record, asynchronously, then yeah that's not going to happen.

**Comment by robconery** [comment]
Right - the original quote was about the MVCC:

> Connection pooling (which we use) mitigates the opening/closing cost and the MVCC will prevent locking, assuming you aren't trying to write twice.

If you try to update a record already in a transaction, it will be locked. Yes, if you use smaller operations, this is less likely to happen. If you use bulk update operations, you have to ensure at the application level that you won't be trying to write to the same record twice. More updates == more risk.

**Comment by Aedaeum** [comment]
Okay, so really I'm not at risk even if the same user sends 5 messages per second, it's not enough data to be considered "bulk".

**Comment by robconery** [comment]
One thing I always recommend to people who are worried about hurting their database is to actively *try and do it*. PostgreSQL is amazingly resilient. In fact I'll go so far as to say that *I would be surprised if you could even dent it*.

I was able to shut PostgreSQL down once, and that was using Elixir when I spawned 100 processes that tried to execute a `select *` over 10,000 rows. Even then, the only problem I had was a disappearing connection pool, so I had some shut downs. I was able to get a throughput of ~8500 queries/second, which is pretty damn slow compared to other systems.

You should be able to get up to the 10s of 1000s easily. Even then, to *truly* know what your bottleneck is you would have to run some profiles with pg_stat_io (see Craig Kerstiens stuff) to know what's slowing things down in your DB. 99% of the time it's a matter of an additional index - and 99.99999% of the time the slowdowns involve reads.

Finally: all of this is kind of moot anyway. If you have millions of writes that need to go in, I'd strongly suggest using a job system like kue. It can batch writes as you need and also execute them concurrently, which is nice.

**Comment by vitaly-t** [comment]
That article, [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost), was written for applications that require scalability, those that already exceed 1,000 queries per second, and on its way to 10,000 queries per second.

Even for applications that do not require consistent scalability, many developers stumble upon how slow data imports can be. When you have an external CSV/file that contains way in excess of 10k records to be inserted or updated, is when you start taking the approach seriously. And this happens way more often than you might think ;)

**Comment by robconery** [comment]
Well I ran a data warehouse for 3 years so I'm quite familiar with importing large chunks of data. I think (as with most discussions surrounding perf) you and I are discussing two different things: speed vs. scaling. They are not the same.

If you had to bulk import millions of rows into a production machine I think you might hear me scream all the way across the world. That needs to be batched into smaller writes so you don't drop your entire production system as the write goes in.

As I said also: yes, in a single op a bulk COPY is going to outperform looped writes. That's obvious. That also will kill your scaling if you have a high-write environment.

All of this is beside the point, which is the database being the "bottleneck" on looped writes. It's not.
