### ISSUE TITLE
Using the in operator with a dynamic list within a SQL file

### ISSUE THREAD

**Issue by jnystrom** [robconery/massive-js#335]
Can I have a sql file like:

```
select * from test1 as t1
inner join test2 as t2 on t1.customerId = t2.id
where t1.status in ($1)
```
where the actual status values are passed in?  Like `[0,1,2]`

I noticed your documentation said you cannot pass in an array as a single argument, so I am not sure how this would work.

**Comment by dmfay** [comment]
Yeah, prepared statements don't work that way. The query engine just takes the parameters you give it and binds them in the appropriate places, it can't expand one parameter into several. With Postgres you can get around this by using the `ANY` array comparison operator instead of `IN`.

**Comment by jnystrom** [comment]
@dmfay so how would I do this using MassiveJS?

**Comment by dmfay** [comment]
Like you'd expect: write your statement `...WHERE field = ANY($n)`, and make sure $n is an array of primitives. It's not a special case except in that it's a Postgres extension on the SQL standard.

**Comment by jnystrom** [comment]
@dmfay thank you very much for your support, you have been amazing supportive and responsive!  It worked, as you said.
