### ISSUE TITLE
DepricationWarning

### ISSUE THREAD

**Issue by weagle08** [robconery/massive-js#348]
I get this warning when initializing the database on Node v7.x (Massive.connect): "DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead." Is there a plan to fix this warning?

**Comment by dmfay** [comment]
We don't use Buffer anywhere, the warning is generated from one or more dependencies so there's not a lot for us to do other than keep those up to date.

**Comment by weagle08** [comment]
Ok, thanks for the update. May go through and update the dependency that is causing it asap.

**Comment by codepunkt** [comment]
Which dependency is it?

**Comment by dmfay** [comment]
At least one such usage is in the pg driver's buffer-writer dependency, but there may be others if you grep node_modules.
