### ISSUE TITLE
add promises api

### ISSUE THREAD

**Issue by luisrudge** [robconery/massive-js#37]
is that possible? :)

**Comment by robconery** [comment]
Not a fan of promises TBH - lots of noise for very little return.

**Comment by neverov** [comment]
It's quite easy to do by yourself if you want to use promises. For example, if you use [bluebird](https://github.com/petkaantonov/bluebird) library you can try the following:
```javascript
var Promise = require('bluebird'),
    massive = require('massive');

var connect = Promise.promisify(massive.connect);
var query = function(f) {
  return connect({ connectionString: yourConnectionString }).then(function(db) {
    if (db.yourTable) {
      Promise.promisifyAll(db.yourTable);
    }
    return f(db);
  });
};
```
and then you can use it like this:
```javascript
var queryPromise = query(function(db) {
  return db.yourTable.findOneAsync(id).then(function(result) {
    // do smth
    return result;
  });
});
```

**Comment by luisrudge** [comment]
Nice. THanks!

**Comment by paulxtiseo** [comment]
@neverov, so did you find that calling something like `Promise.promisifyAll(db)` did not promisify the table-specific functions, like `db.yourTable.save()`? Seems like `promisifyAll(db)`, when I used it, only did the built-in top-level methods and the postgresql-derived functions. What, if anything, did you do in practice for this?

**Comment by neverov** [comment]
@paulxtiseo there is an example above, it looks a little bit dirty but definitely worked at the time. I mean:
```javascript
return connect({ connectionString: yourConnectionString }).then(function(db) {
  // THIS PART 
  if (db.yourTable) { 
    Promise.promisifyAll(db.yourTable);
  }
});
```

**Comment by robconery** [comment]
I know this will cause some problems but I don't want to add promises at this time.
