### ISSUE TITLE
Support Oracle

### ISSUE THREAD

**Issue by jbogard** [robconery/massive-js#38]
I noticed that this project does not support Oracle.

Please support Oracle.

Also, is this project still being actively developed? The last commit was over 4 hours ago.

**Comment by FransBouma** [comment]
I agree, the support for other databases is piss poor. At least add Sybase Adaptive Server Enterprise support, it now looks like it only supports the databases the maintainer likes.

**Comment by xivSolutions** [comment]
@jbogard- you DID see we closed out the SQL Server issue no? Rob thought the SQL Server support should be the priority, you can tell from his closed issue. To get the Oracle support you will need to upgrade to Massive-js Enterprise Edition. ;)

**Comment by mstum** [comment]
While we're on it, can we also get native support for XML datatypes, incl. XPath Queries and XSLT to hook it directly into a view engine?

**Comment by robconery** [comment]
![trollface_17-403125921](https://cloud.githubusercontent.com/assets/78586/6650975/c59c9a10-ca2e-11e4-8aa2-975806d06e94.jpg)
