### ISSUE TITLE
Add Tests for Function Support

### ISSUE THREAD

**Issue by xivSolutions** [robconery/massive-js#39]

**Comment by robconery** [comment]
LOL I have a spec file here that I didn’t git add for some reason! I pulled your changes down and you had almost the exact same file :).



On March 15, 2015 at 6:20:33 AM, John Atten (notifications@github.com) wrote:

Closed #39 via 1e8628a.

**Comment by xivSolutions** [comment]
That's funny. Yeah, I often find that I'm thinking/working on something,
and you push up that very thing (was thinking to myself yesterday "I wonder
if it might make sense to build out an auth/membership package for this."
Got back to the hotel, and voila - there it is in your twit-feed). I am not
as proficient with Node/js as I am with .net (yet), so it goes a little
slower.

This is a cool project man.
