### ISSUE TITLE
Filter by Namespace On Init

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#47]
On spin up we read all tables from the database and attach to the root object. I think it would be nice to allow for a specification for which namespaces we want (default is all). This can be done in a number of ways:

 - A single value: "myNamespace"
 - An array: ["myNamespace", "myOtherNamespace"]
 - Or an explicit declaration of "all": "*"

The last is the default. We could then fashion the Table Query to pull only the namespace specified.

**Comment by xivSolutions** [comment]
@robconery - See the branch `filters_review`. Would like your eyes on this. 

I took this first stab sticking to the "sql in a file" model. I am not yet happy with the tests - they all pass, and they show it all appears to be working. However, they are fragile, and I think could be imrpoved. I'll work on that while I'm traveling this week. 

In theory, we should have:

Filter by schema and/or blacklist:

Include only tables from specified schemas:
``` javascript
massive.connect({connectionString: connString, schema: 'myschema'}, function (err, res) {}

// should return db with only tables from myschema loaded
```

Multiple schemas:
``` javascript
massive.connect({connectionString: connString, schema: ['myschema', 'secrets']}, function (err, res) {}

// should return db with only tables from myschema and secrets loaded
```

restrict schemas, but allow explicit exceptions
``` javascript
massive.connect({connectionString: connString, schema: 'myschema', exceptions: 'secrets.__secret_table'}, function (err, res) {}

// should return db with tables from myschema and secrets loaded, and any tables listed in exceptions (must ref by schema name unless public)
```

blacklist using a pattern:
``` javascript
massive.connect({connectionString: connString, schema: 'myschema', blacklist: 'myschema.a%'}, function (err, res) {}

// should return db with tables from myschema but excludes tables in myschema matching the pattern mychema.a% (must ref by schema name unless public)
```

blacklist using a pattern, with exceptions:
``` javascript
massive.connect({connectionString: connString, schema: 'myschema', blacklist: 'myschema.a%', exceptions: myschema.artists}, function (err, res) {}

// should return db with tables from myschema but excludes myschema.albums, includes myschema.artists
```

whitelist tables:
``` javascript
massive.connect({connectionString: connString, whitelist: 'products, myschema.artists}, function (err, res) {}

// should return db with only the products and myschema.artists tables
```

Whitelist trumps everything else. 

Etc. If you approve of the general direction, I will make some improvements, and push to master. 

Thoughts?

**Comment by robconery** [comment]
Thanks Jon - I'm in Greece currently and have had no internet until now!
