### ISSUE TITLE
Add a function filter/killswitch for init

### ISSUE THREAD

**Issue by robconery** [robconery/massive-js#50]
Currently we load all functions on init, and this should have some rules to it so we avoid loading things from extensions (like `pg_crypto`). This should be a LIKE filter:

```
massive.connect({db: "myDB", excludeFunctions : "xx_%"}
```

We should also have an option for ignoring function load altogether:

```
massive.connect({db: "myDB", functions : false}
```

**Comment by xivSolutions** [comment]
Should function  loading be affected by the schema, blacklist/whitelist filters, or should it be independent?

For example, if we do this (and apply no function filter as per the issue topic here):
```javascript
massive.connect({connectionString: connString, schema: 'myschema'}, function (err, res) {}

// should return db with only tables from myschema loaded
```

Should functions not in `myschema` still be loaded, or should this limit to loading only functions in the specified schema(s)?

**Comment by robconery** [comment]
Good question. Hmmm - this is getting complicated I spose :). For now let's ignore schema...

**Comment by xivSolutions** [comment]
Appears to work correctly. Included schema as part of filter though, otherwise we are asking for an issue the first time someone has a name collision. Also, to maintain consistency with the way tables are filtered (see the tests).
