### ISSUE TITLE
path.parse is only available in node 0.12

### ISSUE THREAD

**Issue by paulovieira** [robconery/massive-js#56]
Massive uses `path.parse` in the `walkSqlFiles` helper function. However this method is only available in node 0.12 (and not in 0.10). 

This means that the users can't use the "SQL Files as Functions" functionality. If I place a .sql file in the "db" directory, massive will crash immediately with:

```
TypeError: Object #<Object> has no method 'parse'
```

**Comment by robconery** [comment]
I believe it means that users can’t use this functionality *unless they’ve upgraded*, which, in your case, appears to be the problem. So my choice is to change the codebase, impacting our current users, publish a change and make sure nothing breaks… or *you just upgrade your Node install*.

As a software developer, which would you choose?



On April 28, 2015 at 2:46:44 PM, Paulo Vieira (notifications@github.com) wrote:

Massive uses path.parse in the walkSqlFiles helper function. However this method is only available in node 0.12 (and not in 0.10).

This means that the users can't use the "SQL Files as Functions" functionality. If I place a .sql file in the "db" directory, massive will crash immediately with:

TypeError: Object #<Object> has no method 'parse'

**Comment by paulovieira** [comment]
I note a bit of irony in your reply, which is probably justified given the lack of clarity in my message.

Obviously this is only a "problem" for those who don't want (or can't) upgrade from 0.10 to 0.12. But given that 0.12 is only a few weeks old and people have had apps in production using 0.10 for a long time, I would say the percentage of developers who would like to try massive and are using 0.10 is quite large. 

I would suggest at least adding the "engines" property to package.json (or simply adding the 0.12 requirement to the readme). If that information is not present, I would assume the module works with 0.10.

By the way, the parse-filepath module seems to be a good substitute for `path.parse`:
https://www.npmjs.com/package/parse-filepath

If there's interest, I'm happy to submit a PR with this change, thus making massive compatible with 0.10 (hopefully).

**Comment by robconery** [comment]
Thank you :) and yes, that would be lovely (a PR)

**Comment by robconery** [comment]
Solved with PR
