### ISSUE TITLE
Command to start the REPL doesn't work

### ISSUE THREAD

**Issue by paulovieira** [robconery/massive-js#59]
The readme says the REPL can be started with the command `bin massive`. But in Linux (ubuntu 14.4) this doesn't work (I get a `No command 'bin' found, did you mean: ...`). Am I missing something?

However I successfully started the REPL in the normal way: `./bin/massive.js`

**Comment by robconery** [comment]
Nicely done - good job :).

**Comment by paulovieira** [comment]
Your sarcasm is unnecessary. My intention when opening this issue was simply to report something that is not (or was not) working and a possible workaround, so that others won't loose time.

I see the readme wasn't changed about this. I can submit a pr if you're interested.

**Comment by robconery** [comment]
Honestly wasn't being sarcastic; sorry mate. I've been writing a tutorial this past week and I'm fairly certain that tone bled into my response :). Glad you figured it and got it working - if you'd like to PR the README for some credit go for it.
