### ISSUE TITLE
How do you prefer to handle schema changes?

### ISSUE THREAD

**Issue by sidwood** [robconery/massive-js#63]
I’m curious as to how other developers using massive.js handle schema changes over time in their applications. Do you just add timestamped ad-hoc sql migration scripts or are you creating custom up/down migration tools around massive.js?

Btw, thanks @robconery for writing this. I’m wrapping up my first project using this library and it’s been fantastic.

**Comment by robconery** [comment]
Yay! And you're welcome :). Here's what I do when building up a schema:
https://github.com/robconery/pg-auth

The idea is to use tests to drive the build, when you're done you have a set of nice SQL files. When you need to migrate to a new schema my preference is to use a tool like Navicat to create a diff script. Or just build one as you go... but yes generally you have to keep track of this stuff.

OR you can use a node-based migration framework, of which there are many :).
