### ISSUE TITLE
Case Issue With Functions

### ISSUE THREAD

**Issue by paulxtiseo** [robconery/massive-js#64]
_Requested as its own ticket from issue #26_

I have a function in postgresql as:
```sql
CREATE OR REPLACE FUNCTION "getOrderByOperator"(IN opid bigint)
```
Now, MassiveJS gives me a `db.getOrderByOperator()` to call. But, when I call it, it errors with `[error: function getorderbyoperator(unknown) does not exist]`. True, it does not exist, but only because it's (I'm assuming) lowercasing the whole thing rather than using it as-is.

Is this fixed? Fixable? Is there a workaround short of constraining to snake casing or abandoning MassiveJS altogether?

**Comment by xivSolutions** [comment]
This is fixable. I can push a fix in the next day or two. Traveling atm.

**Comment by paulxtiseo** [comment]
I think I have a fix. I am changing line 263 from:

`sql = "select * from " + fn.name;`
to
`sql = util.format("select * from \"%s\"", fn.name);`

Does that seem correct? This will force all sql to use quoted identifiers.

**Comment by xivSolutions** [comment]
Do the tests pass when you run them with this in place?

**Comment by paulxtiseo** [comment]
:+1: 

```
$ npm test

> massive@2.0.4 test /Repositories/~Personal/massive-js
> mocha .



  0 passing
```

**Comment by xivSolutions** [comment]
Uh...zero passing?

**Comment by paulxtiseo** [comment]
Ah, true. I didn't see any red, so I too quickly assumed passing tests.

So, not sure why tests didn't run? I did run `npm test` from the CLI in the Massive root directory... Looking into it...

**Comment by xivSolutions** [comment]
If you have mocha installed you should be able to just do 'mocha' from the project root

**Comment by paulxtiseo** [comment]
Strange. Never had this before:
```
[~/Repositori...onal/massive-js] $ mocha


  Document queries
    1) "before all" hook

  0 passing (34ms)
  1 failing

/usr/local/lib/node_modules/mocha/lib/reporters/base.js:197
      var match = message.match(/^([^:]+): expected/);
                          ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/mocha/lib/reporters/base.js:197:27
    at Array.forEach (native)
    at Function.exports.list (/usr/local/lib/node_modules/mocha/lib/reporters/base.js:161:12)
    at Spec.Base.epilogue (/usr/local/lib/node_modules/mocha/lib/reporters/base.js:317:10)
    at Runner.emit (events.js:129:20)
    at Runner.uncaught (/usr/local/lib/node_modules/mocha/lib/runner.js:593:8)
    at process.uncaught (/usr/local/lib/node_modules/mocha/lib/runner.js:612:10)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
```

**Comment by xivSolutions** [comment]
Is there a database named "massive" defined in your Postgres cluster?

**Comment by paulxtiseo** [comment]
Stupidly, that was it. I modified the connection string and it ran the tests.

43 tests failed, but all for `TypeError: Cannot read property 'findDoc' of undefined`. Or, for searchDoc.

**Comment by xivSolutions** [comment]
See the conn string in the tests/helpers. Massive cannot create the database itself. You need to add an empty database matching the name in the con string, and you may need to add the login creds as well...

**Comment by xivSolutions** [comment]
Comments crossed in transit...

**Comment by xivSolutions** [comment]
This fix works for me, and all tests still pass. I'm going to merge this, but then add some tests for this case.

**Comment by xivSolutions** [comment]
@paulxtiseo - not certain what's going on with your failing tests for `findDoc` and `searchDoc`. I merged your changes, all tests pass, and I added a couple tests to test the escape stuff you put in. All tests pass. :-)
