### ISSUE TITLE
overloaded functions

### ISSUE THREAD

**Issue by warmuuh** [robconery/massive-js#67]
i am having issues with overloaded functions, i guess they are not working properly...
when calling a function that is overloaded, it tells me for example:
`bind message supplies 4 parameters, but prepared statement "" requires 3`

thats because there is also a function with same name and 3 parameters...

**Comment by xivSolutions** [comment]
Not sure, but you might need to namespace your functions. While Postgres may support function overloading, I'm pretty sure JS will simply "hoist" the last one it finds.

There may be a solution of some sort for this in the Wayne load functions. I'll investigate.

Meantime, trying to load two functions of the same name into the massive instance is simply replacing the first with the second.

**Comment by warmuuh** [comment]
yes... thats what i thought... i helped myself with a small hack:

**Comment by xivSolutions** [comment]
@warmuuh - It's an interesting problem. Solving it may require more complexity than we want to introduce, but it is worth exploring. 

FYI, your hack didn't come through in your comment.

**Comment by warmuuh** [comment]
i edited the comment... but it mainly adds the parameter-part of the sql dynamically based on the given number of arguments
