### ISSUE TITLE
Error "inconsistent types deduced" for table save method 

### ISSUE THREAD

**Issue by stephensong** [robconery/massive-js#68]
Hi guys,

Found an issue with the table save command.

      db.users.save({userId: userId, userName: newName, updated: dt }, function (err,rslt) {

where userId is the pk of the users table.  It yielded the following error:

"Unhandled rejection error: inconsistent types deduced for parameter $1"

and the generated sql was:

    UPDATE "users" SET "userName" = $1, "updated" = $2
    WHERE "userId" = $1 RETURNING *

which is clearly wrong.  Am I doing something wrong?  I found a simple fix in the source was to simply remove a line from the table save method: 

    if(this.containsPk(args)){
        var pk = this.primaryKeyName();
        //it's an update, use the id to run it
        var where = {};
        where[pk] = args[pk];

commented out the following line:

        //delete args[pk];
        this.update(args,where,next);
    }else{

which seems like it should be ok - yes?  

It seems like the code is written with the implicit assumption that the pk field will always be the last, which in my case was not true (alas!).

thanks.

**Comment by robconery** [comment]
It's removing the PK so you don't update it (which can cause errors) - the position doesn't matter. What's interesting is that the SQL is using `$1` where it *should be using * the actual integer value... unless it's not an integer? What type is it?

**Comment by stephensong** [comment]
Yes, you are right.  The pk is not an integer - it's a uuid.  I see now, thanks.  (Except that I don't quite understand why it appeared to work when I remove the pk delete.)   

Perhaps it should be made more explicit in the docs that (much of) massive is predicated on primary keys being autoincrement (or sequences or whatever pg calls them).

**Comment by xivSolutions** [comment]
When you remove the line you indicated, I believe Massive IS updating the PK - just with the same value. 

@robconery  - Do we want to handle cases where the PK is other than a sequence? It's not TOOO difficult, but it does add some complexity.

**Comment by robconery** [comment]
Hmm - I swear I thought that it was handled. @stephensong would you mind opening another issue for correct handling of UUIDs? Want to be sure you get the credit here - you're helping us quite a lot - thank you!

I could swear we did that but apparently we didn't. @xivSolutions if you get a chance to take a swing at this yay - I'm dealing with 10 hour jetlag for the next few days so I might be a bit muddled. I'll take a crack at it tonight as well.

I'm thinking we need to be sure to cover:

 - uuids, generated or not
 - string keys, generated or not (could be defaulted with a func)

Cheers gents :)

**Comment by robconery** [comment]
Oh and @stephensong to answer your question - Massive *shouldn't* be assuming your key is *any* data type - however (as you can tell) when we were putting this thing together that was our working set :).

**Comment by xivSolutions** [comment]
@robconery On this. I've got a pretty good start here, but now it's past my bedtime on a work night. Should have some cool stuff to push tomorrow night.
