### ISSUE TITLE
getting a working example

### ISSUE THREAD

**Issue by tigernassau** [robconery/massive-js#69]
we really like jsonb but have had trouble using it with current drivers - Massive looks like an answer but we are stuck 
so far the docs are mostly snippets - it's a bit confusing how it all works together in an app and we have several questions - here is some code for a real example - there are several questions in the code - can someone help and turn this into a working example  thks

// in model.js
/* *** postgres setup
***************************************** */
var massive = require("massive");
var configure = function(done) {   
  var connectionString = 
      "postgres://ouruser:ourpassword@localhost/ourdb";
  massive.connect({
  connectionString : connectionString}, function(err, massiveInstance) { 
    app.set('db', massiveInstance);
    done();
  });
};

/* *** signups
***************************************** */
//-----
// first calling the insert(post) from express or hapi
//  ?? need a wrapper function required like below ???

//in app.js 
server.route({
  method: 'POST',
  path: '/api/signup',
  handler: function(request, reply) {
      insertSignup(request.payload)
      .then(function(signup){
        if (signup) {
       //.....
       }
     })
  }
})

// then in  model.js where massive functions are
  //first use a wrapper function to pass params from route 
  var signup = insertSignup(signup, function(err, result) {
    // massive insert function 
    massive.connect({db : "myDb"}, function(err, db){
    // ??? see above
    db.savDoc(doc, {name: "signup"}, function(err,result){
    // ??? what does result come back as ???
    });
  });
});

// now to list the signups 
// in app.js
server.route({
  method: 'GET',
  path: '/api/signupsnew',
  .....
  handler: function(request, reply) {
      getnewSignups(request.payload)
      .then(function(date){
        if (signup) {

// then in model using massive
/* in db/queries/getNewSignups.sql
  'select * from signups where created_at < $1'
*/
massive.connect({db : "myDb"}, function(err, db){
// ??? see above - sould this be connectionString ??
  db.getNewSignups("date", function(err,result){
    return result 
  // ???? is this right ? ? is result a cursor ? 
  });
});

**Comment by xivSolutions** [comment]
The idea here is that you only ever call `massive.connect()` once. There is a load penaly associated with the load process, so once you have a massive instance, you're done with `connect()`, and you want to avoid calling it again. You are correct, the docs really only show a few snippets at this point. 

I am traveling at the moment, and can't actually test the following, so beware I may sprinkle in a few mistakes. The concepts are basically correct though...

Once you use `app.set('db', massiveInstance)` the massive instance is then available as a property on the app object:

``` javascript
var configure = function(done) {   
  var connectionString = "postgres://massive:password@localhost/chinook";
  var scriptsDir = path.join(__dirname, ".", "db");

  // connect to Massive and get the db instance:
  massive.connect({
  connectionString : connectionString}, function(err, massiveInstance) { 

    // Set a reference to the massive instance on Express' app:
    app.set('db', massiveInstance);

    // Let the called know the db is ready...
    done();
  });
};

configure(function() { 
  // Run it...
  http.createServer(app).listen(port);
});
```

From there (for example) you could define another module (say, named 'routes.js') like so:

``` javascript
var Routes = function(app) { 

  app.get('/artists', function (req, res) {
    var db = app.get('db');
    db.artist.find(function (err, artists) { 
      res.send(artists);
    });
  });

  app.get('/artists/:id', function (req, res) { 
    var db = app.get('db');
    var id = Number(req.params.id);
    db.artist.find(id, function (err, artist) { 
      res.send(artist);
    });
  });
};

module.exports = Routes;
```

There are a number of ways to work this into an Express application (and note, I am not an expert on Express at this point). But the over-arching idea is to call `connect()` once at application load, cache the instance, and use that cached instance to work with your database. 

@robconery may have something to add, and/or set me straight in the above, as I think he has worked with Express more extensively than I have.

**Comment by tigernassau** [comment]
thks - agree 100% re only connecting one time - just was not sure how with massive.  your respnse helps and wii rewrite example.  would be good to pick one example whether it is artists, or our lead page signups or even std 5 min blog

**Comment by xivSolutions** [comment]
@tigernassau - agreed on the examples - problem is I am on the road at a tradeshow, and could only do a quick/dirty attempt for the moment. I had to swipe some quick snippets from a file I had available. I wanted to do my best to illustrate the idea with code I know I had running at some point :-)

We will likely update the docs (I will as soon as I return from this trip), and/or do up a blog post, when I can make a better, more consistent example. Rob may also have something to add, but I think he, too, is travelling at the moment.
