### ISSUE TITLE
Flattening Changes Parameter Count

### ISSUE THREAD

**Issue by paulxtiseo** [robconery/massive-js#70]
I call `api.massive.email.save(data,...)` with this data:
```javascript
{ from: 'me@example.com',
  to: { name: 'Me', address: 'me@example.com' },
  cc: 'what@example.com',
  bcc:
   [ { address: 'you@example.com' },
     { name: 'Them', address: 'them@example.com' } ],
  subject: 'This is awesome!',
  text: 'Wha?',
  attachments: [ { path: 'file://path/to/file.txt' } ] }
```

But, the call [Table.prototype.insert](https://github.com/robconery/massive-js/blob/master/lib/table.js#L128) results in this content in `parameters`:
```javascript
[ 'me@example.com',
  { name: 'Me', address: 'me@example.com' },
  'what@example.com',
  { address: 'you@example.com' },
  { name: 'Them', address: 'them@example.com' },
  'This is awesome!',
  'Wha?',
  { path: 'file://path/to/file.txt' } ]
```
which will not work with the generated statement of: `INSERT INTO "email" ("from", "to", "cc", "bcc", "subject", "text", "attachments") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *` The array of objects flattens out to individual values causing a bind error. Am I doing something wrong?

PS: here the `email` table DDL. I realize that my single string in the `cc` field should break things, but I didn't get that far yet. Need to deal properly with the `bcc` field.
```sql
CREATE TABLE email
(
  id bigserial NOT NULL,
  status character varying(8) NOT NULL,
  status_message character varying(8) NOT NULL,
  "from" character varying(254) NOT NULL,
  sender character varying(254),
  "to" jsonb NOT NULL,
  reply_to character varying(254),
  cc jsonb,
  bcc jsonb,
  subject character varying(78) NOT NULL,
  text text,
  html text,
  attachments jsonb,
  creator_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  deleted_at timestamp with time zone,
  CONSTRAINT email_pkey PRIMARY KEY (id),
  CONSTRAINT email_creator_id_fkey FOREIGN KEY (creator_id)
      REFERENCES operator (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```

**Comment by robconery** [comment]
I'll assume you're talking about the `bcc` column and `_.flatten`?

I've run into this before with Postgres - it doesn't want a naked array as a `jsonb` value for some reason (I've had it strip the array even from a single JSON object once, annoying). I've tried to run your query and I get:

```
invalid input syntax for type json
```

Which it clearly is valid JSON, but it's not valid in Postgres for the jsonb *type*.

You have two choices - you can `JSON.stringify()` the array value and it will work just fine (and be stored as valid JSON) or you can use what Postgres wants you to use, something like:

```js
bcc : {
  address : [...]
}
```
The latter solution is a bit clearer to me, but it's up to you. This isn't something Massive can fix (that I can see).
