### ISSUE TITLE
Table.insert can't handle array fields and only returns the first row created

### ISSUE THREAD

**Issue by dmfay** [robconery/massive-js#71]
Table.insert calls db.query after recursively flattening the parameters, so elements in array fields are instead treated as independent parameters. It also only ever returns one row even if multiple rows were created. Pull request incoming.

**Comment by robconery** [comment]
Are you referring to the array PG data type? Yes, we use flatten which is an issue and thank you for the PR! I just want to be sure it doesn't Bork other things so tests are appreciated :)

**Comment by dmfay** [comment]
Yes it is the array type, and I did add some quick tests for insert -- not the most thorough set I've ever written, but it at least validates that insert works with and without arrays. Is there anything else you want covered for this?

**Comment by xivSolutions** [comment]
This works nicely so far! Merged.
