### ISSUE TITLE
Properly Handle Primary Key Alternatives

### ISSUE THREAD

**Issue by xivSolutions** [robconery/massive-js#75]
Issue revealed via @stephensong in issue #68 

Massive currently presumes:

A. All PK's are generated
B. All PK's are serial ints (@dmfay 's PR #74 partially addresses this for UUID Pk's)

We need to handle:

int pks (generated or not)
uuid pks (generated or not)
string pks (generated or not)

In all cases the type is less important than handling the generated/not-generated cases. 

The `.save()` method will currently not correctly handle cases where the PK is not assumed to be generated. 

@robconery When caling `save()` and passing an object which includes the PK field(s!) because the pk is not generated, Massive will skip `insert` and go right to `update`. We CAN detect when a PK is generated or not (I have this working fine, as part of table load). However, when the PK is not-generated, we need to:

A. Employ the new "upsert" functionality introduced in Postgres 5, or;
B. throw, and insist that the caller explicitly specify either `insert` or `update`
C. Some other option I haven't thought of yet...

If we go the "upsert" route, `save` will break for those with older Postgres installations. It is, though, the more elegant way to handle the situation. We could also check for Postgres version, and degrade if necessary into a crude manual handling of a failed `insert` due to key violation, then proceed to `update`, but that's kinda ugly. 

Thoughts?

**Comment by dmfay** [comment]
Admittedly this is kind of a moot point for me since I prefer to generate keys anyway; I do like the idea of using the new upsert functionality, but 9.5 isn't dropping until sometime in Q3 at the earliest so I'd be wary of being a little too bleeding-edge there.

One potential option C would be to allow something along the lines of `db.stuff.save({id: 1, name: 'hi'}, {isNew: true}, function (err, res) {...});` and decide whether to insert or update based on isNew (if present). I'm not too keen on that idea though, because it doesn't really make anyone's life _easier_ -- the level of effort is about as much as required to just call insert or update directly, so I don't see a reason to implement that over option B.

**Comment by xivSolutions** [comment]
@dmfay Totally agree on. Form my perspective there are few cases to use anything other than a generated key, but it does happen. 

The boolean flag thing would work, but it's pretty darn kludgy. 

I think for now, maybe just state explicitly in the docs that tables without generated keys require explicit use of `insert` or `update` and then throw when someone tries to use `save` against such a table (or, alternately, assume `save` in this case means to `update` and let things fail if no matching key exists. Also kuldgy). 

Seems there are a few ways to maybe achieve this using CTE's, or trial `insert`s + return codes, but all seem awfully messy for what should be an edge case.

**Comment by AdrianRossouw** [comment]
One of the unfortunate cases where generating id's doesn't really work is where you might need to shard databases.

**Comment by xivSolutions** [comment]
Agreed. We need to be able to handle non-generated PKs.

**Comment by robconery** [comment]
The first thing I'm wondering is why `insert` or `update` can't be called directly? I believe they can; if you're generating a key in your code it seems reasonable that you can identify which one to use.

Agree with you @AdrianRossouw on sharding etc. In situations like that I usually opt for [a more comprehensive solution](http://rob.conery.io/2014/05/29/a-better-id-generator-for-postgresql/) that involves functions for inserting data. Not always convenient, but neither is sharding. This, also, is another reason for those SQL files.

I believe `save` is the bubble-gum simple method designed for the 80% scenario. I'd prefer not to change it up but I'm open to options that don't add bloat. And right now all I can see coming out of this is a fairly detailed effort at trying to figure out inserts and updates and generated vs. non-generated keys, which *will* produce bugs :).

**Comment by dmfay** [comment]
There's a third assumption missing from the op -- 'all pks are unary'. I don't know if I'll have time to fix this properly so I might just have to hack around it on the application side for now, but an update on a table with a compound primary key is going spectacularly wrong:

```
CREATE TABLE page_checkpoint (
	test_run_id UUID NOT NULL,
	page_number int NOT NULL,
	checkpoint_id UUID NOT NULL,
	status character varying(50) NOT NULL DEFAULT 'unknown',
	reason text
);

ALTER TABLE ONLY page_checkpoint
    ADD CONSTRAINT page_checkpoint_pkey PRIMARY KEY (test_run_id, page_number, checkpoint_id);
```

```
db.page_checkpoint.update({
    test_run_id: chk.test_run_id,
    page_number: chk.page_number,
    checkpoint_id: chk.id,
    status: 'stuff',
    reason: 'things'
}, cb);
```

```
UPDATE "page_checkpoint" 
SET "test_run_id" = $1, "checkpoint_id" = $2, "status" = $3, "reason" = $4
WHERE "page_number" = $5 RETURNING *
```

The query in `tables.sql` doesn't need any adjustment, but loadTables needs to group the resulting rows by schema and name -- right now it processes page_checkpoint three times and the third row declaring page_number to be the primary key wins out. I actually wrote a collapser that builds result trees based on column aliasing (to an arbitrary depth, even!), although that's probably overkill for this.

**Comment by xivSolutions** [comment]
Ahhh.. The compound key issue. I knew this would come up eventually.

This is solveable, but it makes things complicated. I'm wondering if this is a case where we leave it to the user to implement the necessary logic as an SQL query or function for this edge-case, or try to put something in Massive itself to handle compound keys. 

If I can ever get caught up from moving, I'd love to look into it either way. 

Thoughts?

**Comment by dmfay** [comment]
On looking, I'm actually not sure it's too complicated. It's easy enough to detect if you reduce the schema/name/pk rowset before processing the tables; the storage format changes; and then the only place it seems to _matter_ is in the updates, since `find()` on a compound key looks identical to a `find()` on multiple fields.

**Comment by xivSolutions** [comment]
Yeah, I had been messing about with something like that (also detected auto-generated keys and type) before The Big Move. May break it all back out, see what I can get from it. Complexity came from changing things like `getPkName()` and code which depends on a PK ref  to return an array (and callers to expect an array).

Not horrible, but definitely reduced the simplicity.

**Comment by robconery** [comment]
Closing this for now. I think calling `insert` or `update` will work fine. Otherwise use a SQL file.
