### ISSUE TITLE
db.run problems

### ISSUE THREAD

**Issue by tigernassau** [robconery/massive-js#84]
```js
db.signups.find({}, function(err,signups){
    res.render("signups_new", {signups:signups});
  });
```
==> works fine

but 

```js
db.run("select * from signups;",1, function(err,signups){
    res.render("signups_new", {signups:signups}); 
  });
```
==>  does not render  "waiting for localhost"  
the correct array of records is output in the terminal
seems like it is waiting for some sort of closure 

any suggestions?

**Comment by xivSolutions** [comment]
With the run function, looks like you are passing an int as an argument when no corresponding param is indicated in the SQL.

The function is not finding your call back.

**Comment by robconery** [comment]
I don't know if this is an issue for Massive. Perhaps try StackOverflow?

**Comment by tigernassau** [comment]
On 07/02/2015 11:15 AM, John Atten wrote:
>
> With the run function, looks like you are passing an int as an 
> argument when no corresponding param is indicated in the SQL.
>
> The function is not finding your call back.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robconery/massive-js/issues/84#issuecomment-118097101>.
>

Thanks - noticed this too, but earlier effort to leave param out 
resulted in error - but putting in {} passes

so maybe can add another example for select all

db.run("select * from mydocs;", {}, function(err,records) {
   res.render("myview", {records:records});



-- 
Tiger Nassau, Inc.
www.tigernassau.com
