### ISSUE TITLE
Filter postgis function on connect

### ISSUE THREAD

**Issue by zacbarton** [robconery/massive-js#90]
I've got a database that has postgis enabled and connecting takes seconds in-which massive is proxying the 1000+ postgis functions.

It would be great if setting these functions up was avoided either by convention or as a connect option. Actually an option to skip the loadFunctions all together would be handy in some cases.

I managed to reduce the functions.sql queries results from 1081 rows (4500ms) to 43 rows (185ms). I've added what I was playing with in-case its handy?
````
AND routines.routine_name NOT LIKE 'st_%'
AND routines.routine_name NOT LIKE 'box%d%'
AND routines.routine_name NOT LIKE '_st_%'
AND routines.routine_name NOT LIKE 'geography%'
AND routines.routine_name NOT LIKE 'geometry%'
AND routines.routine_name NOT LIKE 'pgis%'
AND routines.routine_name NOT LIKE 'postgis%'
AND routines.routine_name NOT LIKE '_postgis%'
AND routines.routine_name NOT LIKE 'raster%'
AND routines.routine_name NOT LIKE '_raster%'
AND routines.routine_name NOT IN ('addgeometrycolumn', 'dropgeometrytable', 'updategeometrysrid', 'addrasterconstraints', 'droprasterconstraints', 'updaterastersrid', 'addoverviewconstraints', 'dropoverviewconstraints', 'populate_geometry_columns', 'dropgeometrycolumn', 'populate_geometry_columns', '_updaterastersrid')
AND routines.routine_name NOT LIKE '_add_raster%'
AND routines.routine_name NOT LIKE '_drop_raster%'
AND routines.routine_name NOT LIKE 'geomfrom%'
AND routines.routine_name NOT LIKE 'gidx_%'
AND routines.routine_name NOT LIKE 'spheroid_%'
AND routines.routine_name NOT LIKE 'gserialized_gist_%'
-- order by routine_name -- is this needed?
````

**Comment by xivSolutions** [comment]
Ahh... You can do this, just haven't updated the README yet. My bad. 

You can actually filter functions, schemas, and tables (blacklist, whitelist, etc) during the call to `connect`. For some trivial examples, see the tests in the file load_filter_spec.js. 

You can exclude all functions, much as you suggest, like so (from the tests):

```javascript
+  it('excludes functions at load whenever it is told...', function (done) { 
+    massive.connect({connectionString: constr, excludeFunctions: true}, function (err, db) { 
+      assert(db.functions.length == 0);
+      done();
+    });
+  });
```

Or you can us a function blacklist filter (in much the same way you are above) by passing either a comma-delimited string, or an array of strings, and you can use the same "wildcard" syntax as in your code above (here, again, some simple examples from the tests, but you get the idea):

```javascript
+  it('excludes functions with name and schema matching multiiple blacklist patterns as a comma-delimited string argument', function (done) { 
+    massive.connect({connectionString: constr, functionBlacklist: "myschema.artist_%, all_%"}, function (err, db) { 
+      assert(!db.myschema.artist_by_name && !db.all_products && db.myschema.all_albums && db.AllMyProducts);
+      done();
+    });
+  });
+  it('excludes functions with name and schema matching multiiple blacklist patterns as a string array argument', function (done) { 
+    massive.connect({connectionString: constr, functionBlacklist: ["myschema.artist_%", "all_%"]}, function (err, db) { 
+      assert(!db.myschema.artist_by_name && !db.all_products && db.myschema.all_albums && db.AllMyProducts);
+      done();
+    });
+  });
```
Looks like you could take all of the pattern matches from your SQL above, and set them up in an array to pass to the `connect()` method similar to the test examples. 

I think you may be right though, I may "steal" your pattern matches, and set up another simple switch which enables opt-in for including this specific set of functions for PostGis. 

I'll also update the README about the various filtering options available for `connect()`.

In the meantime, take a look at the test file and see how it works for you. Please let us know if you run into problems. The filtering use-cases have been tested in basic form, but have not been exercises extensively in a "real-world" setting.

**Comment by zacbarton** [comment]
Thats exactly what I was after thanks.

Feel free to close this or if you are going to auto filter postgis functions then keep it open as a reminder?

**Comment by xivSolutions** [comment]
I was leaving it open as a reminder. Glad it worked for you!
