### ISSUE TITLE
Casing?

### ISSUE THREAD

**Issue by AlexZeitler** [robconery/massive-js#92]
Maybe I'm doing it wrong but all queries return all database field names completely lowercase.
Is there a chance to get them lowerCamelCase?

**Comment by AlexZeitler** [comment]
I think I can anser it by myself...

`CREATE TABLE CUSTOMER(CompanyName1 VARCHAR(20));`

````
\d+ test
                                   Table "public.customer"
    Column    |         Type          | Modifiers | Storage  | Stats target | Description 
--------------+-----------------------+-----------+----------+--------------+-------------
 companyname1 | character varying(20) |           | extended |              | 
````

And this [SO answer](http://stackoverflow.com/a/20880247/4981358).

**Comment by xivSolutions** [comment]
Yeah, Postgres down-cases your incoming SQL. If you REALLY wanted to, you can modify your SQL like so to maintain casing:

```
CREATE TABLE CUSTOMER("CompanyName1" VARCHAR(20));
```

I would avoid this, though. It makes life harder than it needs to be. Strongly recommend sticking to Postgres conventions unless there is a compelling reason not to. 

Massive accommodates different casing scenarios for the case where you have inherited a database with non-conventional casing, but I recommend staying away from it if you are starting from scratch.

**Comment by AlexZeitler** [comment]
Sure, I'll stick with the Postgres convention.
