### ISSUE TITLE
Support streaming in queries loaded from files

### ISSUE THREAD

**Issue by dmfay** [robconery/massive-js#95]
Turns out adding it to find() wasn't quite enough!

**Comment by stephenkubovic** [comment]
Is there a rough timeline for when this might be landing in npm?

**Comment by dmfay** [comment]
That's up to @robconery but if you're willing to put up with potential instability* in the mean time you should be able to track the master branch in your package.json dependency declaration like so:

```    "massive": "https://github.com/robconery/massive-js/tarball/master",```

* in other words, don't do this on production!

**Comment by robconery** [comment]
I'll get a push out next week...
