### ISSUE TITLE
closing connections

### ISSUE THREAD

**Issue by jfbaquerocelis** [robconery/massive-js#97]
Hi @robconery, I used massivejs and is excellent. But I have a small question, when a function or a query such as is done:
```javacript
db.users.find (100, function (err, res) {
     // code
})
```
How I can close the connection? or does the connection is closed once the function finishes running?

Thank you for reading. *Massivejs* is great

**Comment by xivSolutions** [comment]
Massive makes use of the client pool afforded by [brianc's](https://github.com/brianc) [node-postgres](https://github.com/brianc/node-postgres) library. 

The [client pool handles the disconnect](https://github.com/brianc/node-postgres#client-pooling) for you, and manages available pg client pooling.

**Comment by jfbaquerocelis** [comment]
thanks for your help , now if I understood!

**Comment by xivSolutions** [comment]
@jfbaquerocelis - The short version is, you don't need to worry about closing the connection in your code. The underlying pg lib worries about it for you.

**Comment by jfbaquerocelis** [comment]
@xivSolutions All right bro! Thanks!!
