### ISSUE TITLE
Return an object rather than an array from save() if performing an in-place update by pk

### ISSUE THREAD

**Issue by dmfay** [robconery/massive-js#98]
It's cleaner to do that in Massive imo, instead of having result[0] all over my code. @robconery @xivSolutions I'm not going to merge it in on my own since it does break the existing API -- what do you guys think?

**Comment by xivSolutions** [comment]
My only comment would be that if a method can possibly return more than one result, it should do so consistently. I recognize that the current API is a little inconsistent this way already. I think Rob may feel differently, but my two cents is that if there is a possibility of multiple results, the calling code should be able to assume the return type will be an array (and I actually think the rest of the API might benefit from adherence to this). 

That's just me though. I get the convenience of not having to deal with `result[0]` but it does leave a hole for unexpected results. 

Alternatively, if we decide that an action involving a single, PK-referenced record should return an object, we should make sure that is the case across the API (I think we are inconsistent about this at the moment, but I've been away from the code for a while, dealing with a job transition).

Rob? What say you?

**Comment by robconery** [comment]
I think I agree - result[0] is a pain (I'm living it right now). I like the idea of a doing this for an update (single) as well as an insert (single) - I say... **make it so**

**Comment by dmfay** [comment]
@xivSolutions John, could you merge #99 if you're okay with this? I'm staring at a case where I'm upserting an object and getting varying types back right now :)

**Comment by xivSolutions** [comment]
Done! :-)

**Comment by dmfay** [comment]
thank you!

**Comment by oheard** [comment]
Any idea when this will make it into a stable release? With it being a breaking change I'm guessing we won't see this until 3.x? Also living through this pain (Table.save() in particular resolving to an array or object depending on whether update() or insert() was called).

Glad to see this has been fixed though. :+1:
